import type { JournalDay } from "@seqno/domain"
import { defaultConfig, fileBodyFromTitle, formatJournalDay } from "@seqno/interop"
import { journalFile, shiftDay } from "./journal.ts"
import type { StarterFile } from "./place.ts"

const ids = {
  water: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a01",
  beds: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a02",
  window: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a03",
  association: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a04",
  bigHarvest: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a05",
  split: "0199c3e2-41a7-7d20-8c3f-6a5b9e2f3a06",
} as const

const ref = (id: string) => `((${id}))`

const licenses = {
  bySa4: "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)",
  cc0: "[CC0](https://creativecommons.org/publicdomain/zero/1.0/)",
  publicDomain: "[public domain](https://en.wikipedia.org/wiki/Public_domain)",
} as const

interface Picture {
  readonly alt: string
  readonly file: string
  readonly path: string
  readonly by: string
  readonly license: string
  readonly width?: number
}

const commons = "https://upload.wikimedia.org/wikipedia/commons"

const pictures = {
  beds: {
    alt: "Raised beds of lettuce and salad leaves",
    file: "Raised_vegetable_bed_at_Boreham%2C_Essex%2C_England.jpg",
    path: "thumb/5/52/Raised_vegetable_bed_at_Boreham%2C_Essex%2C_England.jpg/960px-Raised_vegetable_bed_at_Boreham%2C_Essex%2C_England.jpg",
    by: "Acabashi",
    license: licenses.bySa4,
  },
  seedlings: {
    alt: "Tomato and basil seedlings in a seed tray",
    file: "Tomato_and_basil_plant_seedlings_growing_in_tray.JPG",
    path: "2/2e/Tomato_and_basil_plant_seedlings_growing_in_tray.JPG",
    by: "Tomwsulcer",
    license: licenses.cc0,
    width: 420,
  },
  basket: {
    alt: "A basket of ripe tomatoes on straw",
    file: "Tomatoes_in_basket_2020_G1.jpg",
    path: "thumb/6/69/Tomatoes_in_basket_2020_G1.jpg/960px-Tomatoes_in_basket_2020_G1.jpg",
    by: "George Chernilevsky",
    license: licenses.bySa4,
    width: 420,
  },
  tomatoes: {
    alt: "Heirloom tomatoes in green, yellow and orange",
    file: "Tomatoes%2C_heirloom_-_Massachusetts.jpg",
    path: "thumb/4/4f/Tomatoes%2C_heirloom_-_Massachusetts.jpg/960px-Tomatoes%2C_heirloom_-_Massachusetts.jpg",
    by: "Daderot",
    license: licenses.cc0,
  },
  basil: {
    alt: "A bushy basil plant",
    file: "Basil_plant_Meadowbrook_Park.jpg",
    path: "thumb/5/50/Basil_plant_Meadowbrook_Park.jpg/960px-Basil_plant_Meadowbrook_Park.jpg",
    by: "TheTechnician27",
    license: licenses.cc0,
    width: 480,
  },
  sisters: {
    alt: "A corn stalk with beans climbing it and squash spreading at its feet",
    file: "Three_Sisters_planting_visual_graphic.png",
    path: "thumb/d/d7/Three_Sisters_planting_visual_graphic.png/960px-Three_Sisters_planting_visual_graphic.png",
    by: "Garlan Miles",
    license: licenses.bySa4,
    width: 320,
  },
  compost: {
    alt: "A row of wooden compost bins in a community garden",
    file: "Compost_bins_in_Brighthelm_Garden_2023-06-16.jpg",
    path: "thumb/f/f7/Compost_bins_in_Brighthelm_Garden_2023-06-16.jpg/960px-Compost_bins_in_Brighthelm_Garden_2023-06-16.jpg",
    by: "Andy Li",
    license: licenses.cc0,
  },
  pesto: {
    alt: "Pesto in a marble mortar, surrounded by basil leaves",
    file: "Pesto_being_made_in_a_pestle_and_mortar.jpg",
    path: "thumb/1/1f/Pesto_being_made_in_a_pestle_and_mortar.jpg/960px-Pesto_being_made_in_a_pestle_and_mortar.jpg",
    by: "Gopesto",
    license: licenses.bySa4,
    width: 420,
  },
  bush: {
    alt: "Vannevar Bush writing at his desk",
    file: "Vannevar_Bush_portrait.jpg",
    path: "thumb/e/ea/Vannevar_Bush_portrait.jpg/960px-Vannevar_Bush_portrait.jpg",
    by: "Office for Emergency Management",
    license: licenses.publicDomain,
    width: 420,
  },
} satisfies Record<string, Picture>

const picture = (indent: string, { alt, file, path, by, license, width }: Picture) => [
  `${indent}- ![${alt}](${commons}/${path})${width === undefined ? "" : `{:width ${width}}`}`,
  `${indent}  credit:: ${by}, ${license}, [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:${file})`,
]

const page = (title: string, ...lines: ReadonlyArray<string>): StarterFile => ({
  path: `pages/${fileBodyFromTitle(title)}.md`,
  text: lines.join("\n"),
})

export const demoGraph = (today: JournalDay): ReadonlyArray<StarterFile> => {
  const day = (offset: number) => shiftDay(today, offset)
  const date = (offset: number) =>
    `[[${formatJournalDay(day(offset), defaultConfig.journalTitleFormat)}]]`
  const stamp = (offset: number, repeat = "") =>
    `<${formatJournalDay(day(offset), "yyyy-MM-dd EEE")}${repeat}>`
  const journal = (offset: number, ...lines: ReadonlyArray<string>): StarterFile => ({
    path: journalFile(day(offset)),
    text: lines.join("\n"),
  })

  return [
    journal(
      0,
      "- Welcome to the seqno demo graph",
      "- Open [[Getting started]] to see how pages link",
      "- Scroll down for the days before today. This graph is a sample to explore: two weeks of notes on a small vegetable [[garden]], with recipes, projects and a [[Reading list]] along the way.",
      "- Rain all morning, so no watering today. The lettuce seedlings go into bed 2 later this week.",
    ),
    journal(
      -1,
      "- Picked 1.4 kg of tomatoes, the most in one go so far #harvest",
      "  crop:: [[Tomatoes]]",
      "  weight:: 1.4 kg",
      `  id:: ${ids.bigHarvest}`,
      "- Half of them had split after the rain. Why does that happen? #question",
      "\t- Uneven watering, says the [RHS](https://www.rhs.org.uk/vegetables/tomatoes/grow-your-own). Dry soil, then a sudden soak, and the skin can't stretch fast enough. Water deeper and less often.",
      `\t  id:: ${ids.split}`,
      "- TODO Turn the split ones into [[recipes/Roasted tomato sauce]] before they go soft",
      `  SCHEDULED: ${stamp(0)}`,
      "- DONE Rinse and dry the tomato seeds. Twelve envelopes for the [[projects/Seed swap]]",
    ),
    journal(
      -2,
      "- Slugs ate half a row of lettuce in bed 2 overnight. Set two beer traps, then went out with a torch after dark and caught eleven more.",
      "- The seed swap notice is up on the gate: [[projects/Seed swap]]",
    ),
    journal(
      -3,
      "- Started *Braiding Sweetgrass* from the [[Reading list]]. Its chapter on the [[Three Sisters]] is the best explanation of companion planting I've read.",
      "\t- Corn, beans and squash, each one helping the other two. Robin Wall Kimmerer reads it as a lesson in giving back.",
      "- Bed 3: the beans have reached the top of the corn, and the squash leaves are the size of dinner plates.",
    ),
    journal(
      -4,
      "- Saved seeds from the best Black Krim [[Tomatoes]]. Scooped them into a jar of water to ferment for three days, which strips off the jelly so they keep.",
      "\t- Black Krim is an heirloom, so its seeds grow true. Sungold is a hybrid, so I buy those seeds new. [Seed saving on Wikipedia](https://en.wikipedia.org/wiki/Seed_saving)",
    ),
    journal(
      -5,
      "- Pricked out the lettuce, rocket and spinach seedlings into bigger cells. 40 of 48 made it. [[garden]]",
      "- Pulled the first radishes #harvest",
      "  crop:: radishes",
      "  weight:: 300 g",
      "\t- Far too many at once. Next time, sow a short row every two weeks instead of one long one: [succession planting](https://en.wikipedia.org/wiki/Succession_planting).",
    ),
    journal(
      -6,
      "- The basil was about to flower, so it all came in at once #harvest",
      "  crop:: [[Basil]]",
      "  weight:: 350 g",
      "- Made a double batch of [[recipes/Basil pesto]] and froze half in an ice cube tray.",
    ),
    journal(
      -7,
      "- Found an old window for the [[projects/Cold frame]] at the reclaim yard, plus four cedar boards. 38 for the lot, so 22 left in the budget.",
    ),
    journal(
      -8,
      "- Read [A Brief History & Ethos of the Digital Garden](https://maggieappleton.com/garden-history) by Maggie Appleton. Notes on [[Digital gardens]].",
      "- Funny: this graph is about a garden, and it is one.",
    ),
    journal(
      -9,
      "- Turned the [[Compost]] heap. Steaming in the middle, which means it's working.",
      "- Added two buckets of kitchen scraps and a bag of torn-up cardboard. Half green, half brown.",
    ),
    journal(
      -10,
      "- First ripe tomato! One Sungold, eaten standing next to the bed #harvest",
      "  crop:: [[Tomatoes]]",
      "  weight:: 12 g",
    ),
    journal(
      -12,
      "- Sketched a [[projects/Cold frame]]: an old window on a wooden box, so seedlings get a warm, sheltered start.",
      "- WAITING Hear back from the garden committee about a second tap at the far end",
    ),
    journal(
      -13,
      "- Sowed 48 cells of lettuce, rocket and spinach in module trays on the windowsill [[garden]]",
      "\t- Learned this from [Charles Dowding](https://charlesdowding.co.uk): a few seeds per cell, planted out as one clump.",
    ),
    journal(
      -14,
      "- Read [[As We May Think]], from 1945. Eighty years old, and it still describes how a notes app should work.",
    ),
    journal(
      -15,
      "- Started keeping notes here. One page for the [[garden]], and a line or two a day in the journal.",
    ),

    page(
      "Getting started",
      "- seqno is a local-first outliner. Everything you write is a block, and blocks nest.",
      "- This graph is a sample to explore: two weeks of journal, a vegetable [[garden]], two recipes, two projects and a [[Reading list]]. Change anything you like.",
      "- Outline",
      "\t- Click any block to edit it. Enter makes a new block, Tab indents it, Shift+Tab brings it back.",
      "\t- Click a bullet to zoom into a block. Its children come with it.",
      "\t- Click the arrow next to a bullet to fold its children away.",
      "- Link",
      "\t- Type `[[` to link a page, `#` to tag one, and `((` to point at a single block.",
      "\t- Every page lists what links to it at the bottom. [[Ideas]] links back here.",
      "\t- Shift+click a link to open it in the right sidebar.",
      "\t- More in [[Linking]], [[Aliases]], [[Namespaces]] and [[Block refs and embeds]].",
      "- Tasks",
      "\t- TODO Start a block with TODO, or press Ctrl+Enter (Cmd+Enter on a Mac) to cycle it",
      "\t- DOING Type `/` for dates, priorities, headings, code blocks and more",
      "\t- DONE Open this page",
      "\t- Dates, deadlines and priorities are in [[Tasks]].",
      "- Find",
      "\t- Ctrl+K (Cmd+K on a Mac) searches every page and block. Try pesto.",
      "- Query",
      "\t- Queries stay live as you type. This one lists every open task:",
      "\t- {{query (task TODO DOING)}}",
      "\t- More in [[Queries]] and [[Properties]].",
      "- Your notes",
      "\t- This demo lives in your browser and never leaves it. [Local-first software](https://www.inkandswitch.com/local-first/) explains why that matters.",
      "\t- In Chrome or Edge you can open a folder of Logseq markdown instead. seqno writes its edit log next to your files, so try it on a copy.",
    ),
    page(
      "Contents",
      "- This is Contents, a page you write yourself. It stays in the right sidebar (`t r`), so keep the links you want on hand here.",
      "- [[Getting started]]",
      "- **learn by example**",
      "\t- [[Linking]] · [[Tasks]] · [[Queries]] · [[Properties]]",
      "\t- [[Aliases]] · [[Namespaces]] · [[Block refs and embeds]]",
      "- **the garden**",
      "\t- [[garden]] · [[Harvest log]]",
      "\t- [[Tomatoes]] · [[Basil]] · [[Three Sisters]] · [[Compost]]",
      "- **kitchen**",
      "\t- [[recipes/Roasted tomato sauce]] · [[recipes/Basil pesto]]",
      "- **projects**",
      "\t- [[projects/Cold frame]] · [[projects/Seed swap]]",
      "- **reading**",
      "\t- [[Reading list]] · [[As We May Think]] · [[Digital gardens]]",
      "- [[Ideas]]",
      "- There's a second demo graph, a developer's notes: open the graph menu at the top of the left sidebar and pick Developer graph.",
    ),
    page(
      "Ideas",
      "- Loose thoughts go here. This page links back to [[Getting started]].",
      "- LATER Plant tomatoes along the south fence #garden",
      "- Mark what matters: ==like this==",
      "- A herb spiral by the tap: thirsty mint at the bottom, rosemary at the dry top #garden",
      "- Sunflowers on the north edge of bed 3, as a fourth sister for the [[Three Sisters]]",
    ),

    page(
      "Linking",
      "- Write a page's name in `[[ ]]` and it becomes a link. The page doesn't have to exist yet: click the link and seqno makes it.",
      "- Links go both ways. This block links to [[Basil]], so it shows up at the bottom of the Basil page, under Linked references.",
      "- A tag is a link too, written with `#`. Click #question: nobody wrote anything on that page, but it lists every block tagged with it.",
      "- Unlinked references find plain mentions. Open [[Compost]] and look at the bottom: blocks that say compost without linking it are waiting there.",
      "- Hover a link to peek at the page. Shift+click opens it in the right sidebar, so you can read two pages side by side.",
      `- A day is a page too: ${date(-5)} is when the seedlings were pricked out.`,
      "- Links to the web look like [this](https://en.wikipedia.org/wiki/Hyperlink), and a bare address works too: https://docs.logseq.com",
      `- Why bother linking? ${ref(ids.association)}`,
    ),
    page(
      "Tasks",
      "- Start a block with TODO or LATER for things to do, and DOING or NOW for what you're on. Ctrl+Enter (Cmd+Enter on a Mac) cycles them, and clicking the checkbox marks one DONE.",
      "- Use WAITING when the next step is someone else's, and CANCELED to keep a note of what you decided not to do:",
      "\t- CANCELED Build a second compost bin. The shared ones are plenty",
      "- Put a priority after the marker: [#A], [#B] or [#C].",
      "- Type `/Scheduled` or `/Deadline` in a task to pick a date from a calendar. Add `.+2w` inside the date and it comes back every two weeks.",
      "- ## Due in the next two weeks",
      "\t- {{query (and (task TODO DOING) (task.deadline <= +14d))}}",
      "- ## Scheduled for this week",
      "\t- {{query (and (task TODO DOING) (task.scheduled <= +7d))}}",
      "- ## Waiting on someone",
      "\t- {{query (task WAITING)}}",
    ),
    page(
      "Queries",
      "- A query asks the graph a question and keeps the answer up to date. Change a block it matches and the results change with it.",
      "- Write one as `{{query ...}}`. Logseq's simple queries work as they are, so the [Logseq query docs](https://docs.logseq.com/#/page/queries) apply here too.",
      "- ## What's on right now",
      "\t- {{query (task NOW DOING)}}",
      "- ## Every tomato harvest, found by its crop property",
      "\t- {{query (property crop [[Tomatoes]])}}",
      "- ## Two filters at once: open tasks with a high priority",
      "\t- {{query (and (task TODO DOING) (priority A B))}}",
      "- ## The same kind of question, written Dataview style",
      "\t- {{query LIST WHERE task.status = waiting}}",
      "- Click the table icon on any query to see its results as a table.",
      "- More queries live where they're useful: [[Tasks]], [[Harvest log]], [[Namespaces]], [[Properties]] and the [[garden]].",
    ),
    page(
      "Properties",
      "type:: guide",
      "read:: 2 minutes",
      "",
      "- The two lines above the first block, type and read, are this page's properties. Click them to edit.",
      "- Blocks can have properties too. Each harvest in the journal carries a crop and a weight:",
      `\t- {{embed ${ref(ids.bigHarvest)}}}`,
      "- Write them as `key:: value` lines under a block's first line. Shift+Enter starts a new line inside a block.",
      "- Put a value in `[[ ]]` and it becomes a link. That's how the [[Tomatoes]] page lists every tomato harvest.",
      "- A few keys do special jobs:",
      "\t- `alias::` gives a page more names. See [[Aliases]].",
      "\t- `id::` gives a block a fixed address, so other blocks can point at it. See [[Block refs and embeds]].",
      "\t- `collapsed:: true` keeps a block folded, like this one. Click its arrow to open it.",
      "\t  collapsed:: true",
      "\t\t- Seed packets keep for about three years in a cool, dry tin.",
      "- Queries can filter on properties. Every page with `type:: recipe`:",
      "\t- {{query (page-property type recipe)}}",
    ),
    page(
      "Aliases",
      "- An alias is another name for the same page. The [[Tomatoes]] page starts with `alias:: tomato, pomodoro`, so [[tomato]] and [[pomodoro]] both go there.",
      "- Tags follow aliases too. [[Harvest log]] has `alias:: harvest`, so every `#harvest` in the journal lands on that page.",
      "- Search finds pages by their aliases. Press Ctrl+K (Cmd+K on a Mac) and type reading.",
      "- Good uses: singular and plural, a short name for a long one, or a name in another language.",
    ),
    page(
      "Namespaces",
      "- A slash in a page name groups pages that belong together, a bit like folders:",
      "\t- [[recipes/Roasted tomato sauce]] and [[recipes/Basil pesto]]",
      "\t- [[projects/Cold frame]] and [[projects/Seed swap]]",
      "- It's only part of the name, so renaming a page moves it to another group.",
      "- Each page is a markdown file, and the slash becomes three underscores: `pages/recipes___Basil pesto.md`. That's how Logseq names its files, and seqno reads them as they are.",
      "- A query can ask about a whole group. Every open task in every project:",
      "\t- {{query (and (namespace projects) (task TODO DOING))}}",
    ),
    page(
      "Block refs and embeds",
      "- Every block has its own address. Type `((` and a few words to find a block, and seqno shows its text wherever you are.",
      `- The watering rule from the garden page, by reference: ${ref(ids.water)}`,
      "- Edit the original and every reference follows. The number beside the original counts its references; click it to see them all.",
      "- Right-click a bullet and pick Copy block ref to get a block's address.",
      "- An embed brings the whole block, children and all, and you can edit it right here:",
      `\t- {{embed ${ref(ids.beds)}}}`,
      "- A page embed brings a whole page:",
      "\t- {{embed [[Ideas]]}}",
    ),

    page(
      "Garden",
      "plot:: 14",
      "beds:: 4, each 1.2 m by 2.4 m",
      "sun:: all day, until the fence shades it after 4 pm",
      "",
      "- Plot 14 at the community garden: four raised beds, a share of the compost bins, and a tap that's always a little too far away.",
      ...picture("", pictures.beds),
      "- ## Beds",
      `  id:: ${ids.beds}`,
      "\t- Bed 1: [[Tomatoes]] and [[Basil]]. Same sun, same watering, picked for the same dinner.",
      "\t- Bed 2: salad. Lettuce, rocket and radishes, sown a short row at a time so something is always ready.",
      "\t- Bed 3: the [[Three Sisters]], corn, climbing beans and squash in one bed. The squash keeps trying to escape toward the compost bins.",
      "\t- Bed 4: herbs and flowers. Marigolds and nasturtiums bring in the bees and keep aphids off the beans. That's [companion planting](https://en.wikipedia.org/wiki/Companion_planting).",
      "- ## What's growing",
      "\t- {{query (page-property type plant)}}",
      "- ## Seedlings",
      ...picture("\t", pictures.seedlings),
      `\t- 48 cells of lettuce, rocket and spinach, sown on ${date(-13)} and pricked out on ${date(-5)}. They go into bed 2 this week.`,
      "- ## Planting schedule",
      "\t- TODO Plant out the lettuce seedlings in bed 2",
      `\t  SCHEDULED: ${stamp(3)}`,
      "\t- TODO Sow a short row of radishes",
      `\t  SCHEDULED: ${stamp(2, " .+2w")}`,
      "\t- TODO Turn the [[Compost]]",
      `\t  SCHEDULED: ${stamp(5, " .+2w")}`,
      `\t- {{embed ${ref(ids.window)}}}`,
      "\t- TODO Cut down the corn once the beans have dried on the stalks",
      `\t  SCHEDULED: ${stamp(12)}`,
      "\t- DONE Fix the drip under the tap",
      "- ## Harvest log",
      "\t- Every harvest goes in the journal with a `#harvest` tag, and the [[Harvest log]] gathers them up.",
      "- ## Rules I keep relearning",
      "\t- Water in the morning, at the roots, not on the leaves.",
      `\t  id:: ${ids.water}`,
      "\t- Feed the soil, not the plants: [[Compost]] on top, no digging.",
      "\t- Slugs come out after rain. Go out with a torch.",
    ),
    page(
      "Harvest log",
      "alias:: harvest",
      "",
      "- Tag a block `#harvest` in the journal and it shows up at the bottom of this page, under Linked references. Nothing to copy, nothing to keep in sync.",
      ...picture("", pictures.basket),
      "- ## This week",
      "\t- {{query (and [[harvest]] (between -7d today))}}",
      "- Each harvest has a `crop::` and a `weight::` property, so queries can find them later. See [[Properties]].",
    ),
    page(
      "Tomatoes",
      "alias:: tomato, pomodoro",
      "type:: plant",
      "bed:: 1",
      "",
      ...picture("", pictures.tomatoes),
      "- Three kinds this year:",
      "\t- [San Marzano](https://en.wikipedia.org/wiki/San_Marzano_tomato): long plum tomatoes for sauce. Thick flesh, few seeds.",
      "\t  ripens:: late",
      "\t- Sungold: orange cherry tomatoes, sweet as candy. Always the first to ripen.",
      "\t  ripens:: early",
      "\t- [Black Krim](https://en.wikipedia.org/wiki/Black_Krim): big, dark and smoky, from Crimea. Splits if you look at it wrong.",
      "\t  ripens:: midway",
      "- Growing",
      "\t- Pinch out the side shoots that sprout between the stem and a leaf, so the plant puts its energy into fruit.",
      `\t- Watering: ${ref(ids.water)}`,
      `\t- Why they split: ${ref(ids.split)}`,
      "\t- The [RHS guide to growing tomatoes](https://www.rhs.org.uk/vegetables/tomatoes/grow-your-own) covers the rest.",
      `- Saving seeds: ferment them in water for three days, rinse and dry. Done on ${date(-4)} for the [[projects/Seed swap]].`,
      "- Cooking: [[recipes/Roasted tomato sauce]]",
    ),
    page(
      "Basil",
      "type:: plant",
      "bed:: 1",
      "",
      ...picture("", pictures.basil),
      "- Pinch off the top just above a pair of leaves, and two shoots grow where there was one. Keep doing it and the plant turns into a bush.",
      `- Once it flowers the leaves turn bitter, so pick everything before then. That happened on ${date(-6)}.`,
      "- Grows next to the [[Tomatoes]]: same sun, same water.",
      "- Most of it becomes [[recipes/Basil pesto]]. [Basil on Wikipedia](https://en.wikipedia.org/wiki/Basil)",
    ),
    page(
      "Three Sisters",
      "type:: plant",
      "bed:: 3",
      "",
      "- Corn, climbing beans and squash, planted together. Each one helps the other two:",
      "\t- the corn is a pole for the beans to climb",
      "\t- the beans add nitrogen to the soil and steady the corn in the wind",
      "\t- the squash's big leaves shade the ground, keep it damp and smother weeds",
      ...picture("", pictures.sisters),
      "- Indigenous peoples across North and Central America have grown these three together for centuries. Some planted sunflowers along the north edge as a fourth sister. [Three Sisters on Wikipedia](https://en.wikipedia.org/wiki/Three_Sisters_%28agriculture%29)",
      "- Robin Wall Kimmerer writes about them in *Braiding Sweetgrass*, on the [[Reading list]].",
      "- How bed 3 went in:",
      "\t- Corn first, in a block instead of a long row, so the wind pollinates it well.",
      "\t  logseq.order-list-type:: number",
      "\t- Beans at the foot of each corn plant once the corn was a hand high.",
      "\t  logseq.order-list-type:: number",
      "\t- Two squash plants around the edge.",
      "\t  logseq.order-list-type:: number",
    ),
    page(
      "Compost",
      ...picture("", pictures.compost),
      "- The shared bins at the end of the path. Everything that grew in the garden comes back here and turns into soil.",
      "- The mix: about half green (kitchen scraps, grass, spent plants) and half brown (cardboard, dry leaves, straw).",
      "\t- Smells bad? It's too wet. Add brown.",
      "\t- Nothing happening? It's too dry. Add green and a splash of water.",
      `- Turn it every couple of weeks to let air in. When it's working, the middle is warm enough to steam, like on ${date(-9)}.`,
      "- Spread it on top of the beds instead of digging it in. The worms do the mixing, and the soil keeps its shape. That's [no-dig gardening](https://en.wikipedia.org/wiki/No-dig_gardening).",
      "- Charles Dowding shows how it's done:",
      "\t- {{video https://www.youtube.com/watch?v=0LH6-w57Slw}}",
      "- [Compost on Wikipedia](https://en.wikipedia.org/wiki/Compost)",
    ),

    page(
      "recipes/Roasted tomato sauce",
      "type:: recipe",
      "serves:: 4",
      "time:: 1 hour 30 minutes",
      "based-on:: [Marcella Hazan's tomato sauce](https://cooking.nytimes.com/recipes/1015178-marcella-hazans-tomato-sauce)",
      "",
      "- [Marcella Hazan's](https://en.wikipedia.org/wiki/Marcella_Hazan) famous sauce is just tomatoes, butter, an onion and salt. This is that, with the tomatoes roasted first, because ours come in every shape and size.",
      "- Ingredients",
      "\t- 1 kg ripe [[Tomatoes]], halved. Split ones are fine",
      "\t- 70 g butter",
      "\t- 1 onion, peeled and cut in half",
      "\t- salt",
      "- Method",
      "\t- Roast the tomatoes cut side up at 200 °C for 40 minutes, until they slump and char at the edges.",
      "\t  logseq.order-list-type:: number",
      "\t- Tip them into a pan with the butter and the onion halves. Simmer gently for 45 minutes, stirring now and then.",
      "\t  logseq.order-list-type:: number",
      "\t- Lift out the onion, crush the tomatoes with a spoon, and salt to taste. It always needs more salt than you think.",
      "\t  logseq.order-list-type:: number",
      "- Freezes well. Good on pasta, better on toast with an egg.",
    ),
    page(
      "recipes/Basil pesto",
      "type:: recipe",
      "serves:: 4",
      "time:: 15 minutes",
      "",
      ...picture("", pictures.pesto),
      "- Pesto alla genovese comes from Genoa, where it's pounded in a marble mortar. A food processor works, but the mortar tastes better. [Pesto on Wikipedia](https://en.wikipedia.org/wiki/Pesto)",
      "- Ingredients",
      "\t- 2 big handfuls of [[Basil]] leaves, about 60 g",
      "\t- 1 clove garlic",
      "\t- 30 g pine nuts",
      "\t- 50 g parmesan, finely grated",
      "\t- 100 ml olive oil",
      "\t- a pinch of coarse salt",
      "- Method",
      "\t- Pound the garlic with the salt to a paste.",
      "\t  logseq.order-list-type:: number",
      "\t- Add the basil a handful at a time, grinding it against the side of the mortar.",
      "\t  logseq.order-list-type:: number",
      "\t- Add the pine nuts and pound again.",
      "\t  logseq.order-list-type:: number",
      "\t- Stir in the cheese, then the oil, a little at a time.",
      "\t  logseq.order-list-type:: number",
      "- To freeze it, leave out the cheese and fill an ice cube tray. Stir the cheese in after thawing.",
    ),

    page(
      "projects/Cold frame",
      "type:: project",
      "status:: building",
      "budget:: 60",
      "",
      "- A [cold frame](https://en.wikipedia.org/wiki/Cold_frame) is a wooden box with a glass lid: a tiny greenhouse for seedlings. Ours uses an old window.",
      "- Parts",
      "\t- an old window, 120 by 60 cm",
      "\t- four cedar boards",
      "\t- two hinges, and a stick to prop the lid open on warm days",
      "- DONE Find an old window",
      "- TODO Cut the boards so the back is taller than the front, for a sloping lid that sheds rain",
      `  SCHEDULED: ${stamp(2)}`,
      "- TODO [#A] Hinge the window onto the frame",
      `  id:: ${ids.window}`,
      `  DEADLINE: ${stamp(10)}`,
      "- LATER Oil the wood so it lasts",
    ),
    page(
      "projects/Seed swap",
      "type:: project",
      "status:: getting ready",
      "",
      "- Once a year the community garden swaps seeds at the shed. Bring what you saved, take what you'll grow. [Seed swaps on Wikipedia](https://en.wikipedia.org/wiki/Seed_swap)",
      "- Bringing",
      "\t- Black Krim [[Tomatoes]], 12 envelopes",
      "\t- Basil, from the plants that bolted",
      "- Looking for",
      "\t- a climbing bean that does well with the [[Three Sisters]]",
      "\t- garlic to plant along the fence",
      "- TODO Label the envelopes: variety, year, plot 14",
      `  SCHEDULED: ${stamp(6)}`,
      "- TODO [#B] Bring the seeds to the swap",
      `  DEADLINE: ${stamp(9)}`,
    ),

    page(
      "Reading list",
      "alias:: reading",
      "",
      "- Books and essays, each with a line on why. NOW is what I'm reading.",
      "- ## Books",
      "\t- NOW [Braiding Sweetgrass](https://en.wikipedia.org/wiki/Braiding_Sweetgrass)",
      "\t  author:: Robin Wall Kimmerer",
      "\t  why:: plants, people and the [[Three Sisters]]",
      "\t- LATER [The Overstory](https://en.wikipedia.org/wiki/The_Overstory)",
      "\t  author:: Richard Powers",
      "\t  why:: a novel about trees. Everyone at the garden says to read it",
      "\t- DONE [Salt, Fat, Acid, Heat](https://en.wikipedia.org/wiki/Salt_Fat_Acid_Heat)",
      "\t  author:: Samin Nosrat",
      "\t  why:: finally understood why my sauce tasted flat. It needed salt",
      "- ## Essays",
      "\t- DONE [As We May Think](https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/), 1945",
      "\t  author:: Vannevar Bush",
      "\t  notes:: [[As We May Think]]",
      "\t- DONE [A Brief History & Ethos of the Digital Garden](https://maggieappleton.com/garden-history), 2020",
      "\t  author:: Maggie Appleton",
      "\t  notes:: [[Digital gardens]]",
      "\t- TODO [Local-first software](https://www.inkandswitch.com/local-first/), 2019",
      "\t  author:: Ink & Switch",
      "\t  why:: why apps like this one keep your notes on your own device",
      "\t- LATER [Evergreen notes](https://notes.andymatuschak.org/Evergreen_notes)",
      "\t  author:: Andy Matuschak",
      "\t  why:: notes that keep growing instead of piling up",
    ),
    page(
      "As We May Think",
      "author:: Vannevar Bush",
      "published:: The Atlantic, July 1945",
      "read-it:: [theatlantic.com](https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/)",
      "",
      ...picture("", pictures.bush),
      "- Bush ran the US science effort during the Second World War. Right after it, he wrote about a problem we still have: we make knowledge faster than we can find it again.",
      "- His answer was the [memex](https://en.wikipedia.org/wiki/Memex), a desk that keeps your books, letters and notes on microfilm. Its big idea was the trail: join any two items, and finding one brings up the other.",
      "- > The human mind does not work that way. It operates by association.",
      `  id:: ${ids.association}`,
      "- Every link in this graph is a small trail like his. See [[Linking]].",
    ),
    page(
      "Digital gardens",
      "- A digital garden is a set of notes you tend over time and share as you go. Half-grown ideas sit next to finished ones, all linked, never quite done.",
      "- Maggie Appleton traces the idea back through the early web in [A Brief History & Ethos of the Digital Garden](https://maggieappleton.com/garden-history).",
      "- It's an old habit in a new place. People kept [commonplace books](https://en.wikipedia.org/wiki/Commonplace_book) for centuries, copying out passages worth keeping. The sociologist Niklas Luhmann filled a [Zettelkasten](https://en.wikipedia.org/wiki/Zettelkasten) with some 90,000 linked index cards.",
      "- This graph is both kinds of garden: notes about a [[garden]], and a garden of notes. Start anywhere and follow the links.",
    ),
  ]
}
