import type { JournalDay } from "@seqno/domain"
import { defaultConfig, fileBodyFromTitle, formatJournalDay } from "@seqno/interop"
import { journalFile, shiftDay } from "./journal.ts"
import type { StarterFile } from "./place.ts"

const ids = {
  loro: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e01",
  oneWriter: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e02",
  reword: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e03",
  onlyNever: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e04",
  oneDoor: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e05",
  cache: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e06",
  overshoot: "0199c3e2-41a7-7d10-9b2e-5f4c8a1d2e07",
} as const

const ref = (id: string) => `((${id}))`

const page = (title: string, ...lines: ReadonlyArray<string>): StarterFile => ({
  path: `pages/${fileBodyFromTitle(title)}.md`,
  text: lines.join("\n"),
})

export const developerGraph = (today: JournalDay): ReadonlyArray<StarterFile> => {
  const day = (offset: number) => shiftDay(today, offset)
  const date = (offset: number) =>
    `[[${formatJournalDay(day(offset), defaultConfig.journalTitleFormat)}]]`
  const stamp = (offset: number, repeat = "") =>
    `<${formatJournalDay(day(offset), "yyyy-MM-dd EEE")}${repeat}>`
  const journal = (offset: number, ...lines: ReadonlyArray<string>): StarterFile => ({
    path: journalFile(day(offset)),
    text: lines.join("\n"),
  })

  return [
    journal(
      0,
      "- NOW seqno lazy open, first step of hardening [[projects/seqno]]",
      "- 509 commits across 22 projects in 6 days. the 95 days before that: 580. the slow part is me reading now, not typing",
      "- week #weekly",
      "\t- shipped: [[projects/seqno]] web app, [[projects/commonplace]], [[projects/brand-it]]",
      "\t- next: seqno hardening, the react-shiki cache",
      "- too many projects open. the fix is a list I trust, not fewer ideas",
    ),
    journal(
      -1,
      "- scope comes from maintainers. an idea post nobody on the team answered isn't direction #rule [[open source]]",
      "- read the primary source myself. a summary of a summary ranked the wrong features first #rule",
      "\t- and before ranking anything, check what people actually get excited about",
    ),
    journal(
      -2,
      "- sidebar idea: a compact rail, plus a hover peek from the left edge [[motion design]]",
      "\t- I move fast and overshoot the edge. ==open slow, close slower==",
      `\t  id:: ${ids.overshoot}`,
      "\t- what felt right: 6px edge strip, 100 ms dwell to open, 200 ms grace after leaving, a 240 ms slide that can reverse halfway",
      "- destructive buttons: arm inline instead of a modal. the button grows, turns orange, second click deletes #idea",
    ),
    journal(
      -3,
      "- [[projects/brand-it]]: a skill that brands a project from its own parts. then branded brand-it with it",
      "- launch video looked washed out once uploaded. it was missing the BT.709 color tags #bug",
      "\t- the ffmpeg line is in [[snippets]]",
      '- commonplace hero was six lines next to the terminal. now: "Everything you\'ve made, saved and said."',
      "\t- copy lives in one file. change it there first, then the site",
    ),
    journal(
      -4,
      "- started [[projects/commonplace]]: all your data in one place, one door for every agent",
      "- agents don't get raw sqlite3. the CLI is the only door, with an MCP subcommand #decision",
      `  id:: ${ids.oneDoor}`,
      "\t- the db is sensitive, and a remote agent can't reach a local socket anyway",
      "- name storm [[naming]]",
      "  collapsed:: true",
      "\t- ~~attic~~ too dusty",
      "\t- ~~annals~~ won't work",
      "\t- ~~chronicle~~ taken twice already",
      "\t- canon is a curated slice. this is everything",
      "\t- commonplace: a commonplace book for the age of agents",
      "- DONE commonplace v0.1 public. template repo + Claude Code plugin",
    ),
    journal(
      -6,
      '- "only" and "never" don\'t belong in instruction files. each one needs a real reason, and there almost never is one #rule',
      `  id:: ${ids.onlyNever}`,
      "- a reply from hex went missing because a plugin prompt said to reply only in one case. same lesson",
      "- DOING go through every hex instruction file for only/never [[projects/hex]]",
    ),
    journal(
      -7,
      "- hex launch bar, written down so I stop moving it [[projects/hex]]",
      "\t- hackers self-host the alpha",
      "\t- someone's parents can use the hosted one within a day of launch",
      "- my prompts are instructions. anything I state should land in memory the moment I say it",
      "- week #weekly",
      "\t- shipped: hex to myself, seqno phase 0",
      "\t- next: seqno web app",
    ),
    journal(
      -8,
      "- forks that maintain themselves: each patch is a short markdown spec, CI re-applies them on every upstream release [[open source]]",
      "\t- the [herdr fork](https://github.com/AVGVSTVS96/herdr) is the proof of concept",
      '- buzz fork "nightly" = the newest upstream main commit with green CI. upstream has no nightlies, so main is allowed to break',
      "- LATER package the fork bot so anyone can point it at any repo #idea",
    ),
    journal(
      -10,
      "- seqno web build. agents ran the phases, my part was reading the design harness: 12 screens next to Logseq, light and dark [[dark mode]]",
      "- flows find things by role, not CSS class. same hooks a screen reader uses",
      "- TODO make e2e fail on errors inside the core worker too, not only page errors [[projects/seqno]]",
    ),
    journal(
      -11,
      "- desktop = Electron #decision #seqno",
      "\t- same Chromium as the web build, so the web tests cover desktop. Tauri and Electrobun get Safari's engine on a Mac",
      "- SQLite is a cache: `journal_mode=memory`, `synchronous=off` #decision #seqno",
      "\t- the edit log can always rebuild it. 5.6 ms p95 per keystroke relaxed vs 14.1 ms durable",
      "- iCloud on iOS needs the paid developer program, and container ids can never be deleted. pick bundle and container ids once #rule",
    ),
    journal(
      -13,
      "- queries: Logseq syntax first, Dataview second #decision #seqno",
      "\t- dropped a third, Datalog-looking syntax. it looks like advanced queries but has no joins. wrong expectations",
      "\t- the same 15 real queries: 763 chars as Logseq, 975 as Dataview, 1,119 as Datalog",
      "- CANCELED Safari local-only mode. no writable folder picker means it never syncs. one less adapter to test",
    ),
    journal(
      -14,
      "- one writer per file in the synced folder. delete only after another device confirms the snapshot #decision #seqno",
      `  id:: ${ids.oneWriter}`,
      "\t- without the confirm step, 7 of 16 sim runs lost ops",
      "\t- with it: 1,000 runs, 0 lost ops",
      "- `tree.has(undefined)` crashes inside wasm and the doc is dead after. validate every id before it reaches Loro #bug",
    ),
    journal(
      -16,
      "- [[projects/seqno]] phase 0: spikes before any app code. measure first",
      "- Loro is the source of truth, markdown is the mirror #decision #seqno",
      `  id:: ${ids.loro}`,
      "\t- markdown as truth = two devices editing one page write one file. the synced folder keeps one or makes a conflict copy. a CRDT merges both [[CRDTs]]",
      "\t- a keystroke: 0.14 ms on the web, 0.053 ms on iOS. ~100x under a frame",
    ),
    journal(
      -18,
      "- one reworded line beat three new rules [[prompting]]",
      `  id:: ${ids.reword}`,
      '\t- before: "you can hand work off to subagents"',
      '\t- after: "you will often hand off work to keep your own context small"',
      "\t- same rule, but now it says when",
    ),
    journal(
      -20,
      "- voice notes for hex: local Whisper took 27 s on a 50 s note. no",
      "- a newer 164 MB model does the same note in under 2 s, and it's more accurate. only found it because someone posted it #rule",
      "\t- never pick a model from memory. check what shipped this month",
      "- words it keeps mishearing: herdr, shadcn, tmux, TanStack, react-shiki. a dictionary file, not a longer prompt",
    ),
    journal(
      -22,
      "- started [[projects/hex]]. an assistant that lives in Telegram, built on Claude Code",
      "- build on the harness, not against it. Claude Code already did the hard part #rule",
      "- the whole thing should stay small enough to read in one sitting",
    ),
    journal(
      -25,
      "- found why a big downstream app dropped our code blocks: every remount re-tokenized on the main thread #bug [[projects/react-shiki]]",
      "\t- they wrote their own LRU cache. that cache should live in react-shiki",
      "- TODO [#B] built-in highlight cache for react-shiki, keyed by code + lang + theme",
      `  id:: ${ids.cache}`,
      `  SCHEDULED: ${stamp(2)}`,
    ),
    journal(
      -27,
      "- react-shiki 0.11 out, just dependency bumps [[projects/react-shiki]]",
      "- downloads look huge but ~70% is one app pinned to 0.9.3. organic is flat around 110k a week",
      "\t- the number to watch is the organic line, not the total",
    ),

    page(
      "Contents",
      "- [[About this graph]]",
      "- [[review]]: open tasks, decisions, what's due",
      "- **projects**",
      "\t- [[projects/seqno]]",
      "\t- [[projects/hex]]",
      "\t- [[projects/commonplace]]",
      "\t- [[projects/brand-it]]",
      "\t- [[projects/react-shiki]]",
      "\t- [[projects/prompt-picker]]",
      "- **topics**",
      "\t- [[CRDTs]] · [[motion design]] · [[dark mode]] · [[prompting]] · [[open source]] · [[naming]]",
      "- [[reading]] · [[snippets]] · [[people]]",
      "- **on it now**",
      "\t- {{query (task NOW DOING)}}",
    ),
    page(
      "About this graph",
      "author:: [[Bassim Shahidy]]",
      "",
      "- Bassim Shahidy's demo graph, distilled from his prompt history.",
      "- This is a typical developer's Logseq graph. It shows how a developer can still get value from notes in the age of AI, when most of what we type goes to agents.",
      "- Some people take a lot more notes than others. My circle are developers who put most of their text into prompts, and this is for them. I don't take notes myself, so I went back through my prompts and kept what I'd want written down:",
      "\t- decisions and why: [[decision]]",
      "\t- rules I learned the hard way: [[rule]]",
      "\t- bugs worth remembering: [[bug]]",
      "\t- ideas for later, and a line or two a day in the journals",
      "- The agents write the code, the docs and the commit messages. This is the place I write.",
      "- Start with Contents in the right sidebar (`t r`), or the [[review]] page.",
      "- Bassim",
    ),
    page(
      "review",
      "alias:: dashboard",
      "",
      "- TODO weekly review",
      `  SCHEDULED: ${stamp(2, " .+1w")}`,
      "- ## open tasks",
      "\t- {{query (task NOW DOING TODO)}}",
      "- ## due in the next two weeks",
      "\t- {{query (and (task NOW DOING TODO) (task.deadline <= +14d))}}",
      "- ## decisions, last two weeks",
      "\t- {{query (and [[decision]] (between -14d today))}}",
      "- ## later",
      "\t- {{query (task LATER)}}",
      "- ## weeks",
      "\t- {{query [[weekly]]}}",
    ),

    page(
      "projects/seqno",
      "alias:: seqno",
      "type:: [[project]]",
      "status:: hardening",
      "tags:: local-first, outliner",
      `started:: ${date(-16)}`,
      "",
      "- Logseq, rebuilt local-first on Loro, SQLite and Effect. web first, then iOS and desktop",
      "\t- [repo](https://github.com/AVGVSTVS96/seqno) · [app](https://seqno-app.vercel.app) · [site](https://seqno.vercel.app)",
      "- ## decisions",
      "\t- {{query (and [[decision]] [[seqno]])}}",
      "- ## open",
      "\t- TODO [#A] peer ids get reused when some update files aren't downloaded yet. devices then disagree for good, silently",
      `\t  DEADLINE: ${stamp(5)}`,
      "\t- TODO [#A] two devices both create today's journal before syncing: two pages, one name, graph won't open",
      "\t- TODO [#B] check in a 50k-block benchmark that fails when open or typing goes over budget",
      `\t  SCHEDULED: ${stamp(1)}`,
      "\t- LATER turn on the markdown mirror so Logseq sees seqno's edits",
      "- ## hardening, in order",
      "\t- open lazily: newest snapshot, visible page first, index kept on disk",
      "\t  logseq.order-list-type:: number",
      "\t- close the data-safety gaps, peer ids and duplicate names first",
      "\t  logseq.order-list-type:: number",
      "\t- keep the edit log small on one device, and show save state",
      "\t  logseq.order-list-type:: number",
      "\t- markdown mirror on",
      "\t  logseq.order-list-type:: number",
      "\t- sync sim on the real graph, then the full 1,000 runs of 10k ops",
      "\t  logseq.order-list-type:: number",
      "- ## numbers",
      "\t- {{embed [[projects/seqno/numbers]]}}",
      "- ## open question",
      "\t- lazy open vs backlinks: a page's references need the index, and the index needs every page. what loads first? #question",
      "- homepage hero follows Buzz's opening screen. credited to [[Wes Billman]] in the README",
    ),
    page(
      "projects/seqno/numbers",
      "- 50k blocks on 1,865 pages, headless Chrome and the iOS simulator",
      "- full open: 1,181 ms web, 2,435 ms iOS",
      "- page list + first page: 388 ms web, 178 ms iOS",
      "- keystroke p95: 0.14 ms web, 0.053 ms iOS",
      "- merge 1k remote edits, warm: 48.9 ms web, 57.6 ms iOS",
      "- slowest of 15 real queries, p95: 12.9 ms",
      '- loro-ffi at opt-level 3 instead of "z": 2-6x faster for ~2 MB more app',
    ),
    page(
      "projects/hex",
      "type:: [[project]]",
      "status:: alpha",
      "tags:: assistant, claude-code",
      `started:: ${date(-22)}`,
      "",
      "- a personal assistant that lives in your Telegram, built on Claude Code. [repo](https://github.com/AVGVSTVS96/hex)",
      "- how it should behave",
      "\t- it just works. that's the whole feature",
      "\t- behavior follows real events: hooks, signals, status. never a timer standing in for one",
      "\t- anything built for hex keeps working with stock Claude Code",
      "- the rule I keep relearning:",
      `\t- {{embed ${ref(ids.onlyNever)}}}`,
      "- TODO DMs get their own session on every connector, not forwarded into the main thread",
      "- TODO [#B] a false safety flag recovers by itself: same model, reworded, work kept. tell me only after a few in a row",
      "- LATER pick effort and model per thread, from any chat",
    ),
    page(
      "projects/commonplace",
      "type:: [[project]]",
      "status:: v0.1",
      "stack:: Bun, bun:sqlite, plain TypeScript",
      `started:: ${date(-4)}`,
      "",
      "- your personal data kit for agents. [repo](https://github.com/AVGVSTVS96/commonplace)",
      "- all of it, not just GitHub: texts, mail, saves, watch history, charges. that's how an agent learns your intent and judgment",
      `- ${ref(ids.oneDoor)}`,
      "- redact at import, not at read. what never gets in can't leak #decision",
      "- the README sorts sources: built in, one setup step away, coming. people should see what works today",
      "- brand: paper `#FAF9F6`, one red `#D2451E`, Ioskeley Mono (Iosevka shaped like Berkeley Mono, OFL)",
      "- TODO live X source through the official API, pay per use. no scraping",
      "- LATER docs pages",
    ),
    page(
      "projects/brand-it",
      "type:: [[project]]",
      "status:: shipped",
      `started:: ${date(-3)}`,
      "",
      "- a skill for coding agents: brand a project from its own parts, all built as code",
      "\t- [repo](https://github.com/AVGVSTVS96/brand-it) · [site](https://brand-it-seven.vercel.app)",
      "- name, wordmark, palette, type, site, link preview, README header, launch post, launch video",
      "- the brand comes from the product's own parts, not a mood board",
      "- every page checked at every width, light and dark, before it's done [[dark mode]]",
      "- TODO social preview image still needs a manual upload on GitHub",
    ),
    page(
      "projects/react-shiki",
      "type:: [[project]]",
      "status:: maintained",
      "tags:: syntax highlighting",
      "",
      "- syntax highlighting hook and component for React, powered by [Shiki](https://shiki.style). [repo](https://github.com/AVGVSTVS96/react-shiki)",
      '- > "one of the best implementations of syntax highlighting i\'ve ever seen in react" --[[Theo Browne]]',
      "- where it stands",
      "\t- ~1.5M downloads a month, mostly one app pinned to 0.9.3",
      "\t- organic ~110k a week, flat",
      "\t- [Streamdown](https://github.com/vercel/streamdown) is the main alternative for streaming markdown",
      `- next: ${ref(ids.cache)}`,
    ),
    page(
      "projects/prompt-picker",
      "type:: [[project]]",
      "status:: maintained",
      "",
      "- a TUI and CLI to search every prompt I've sent to Claude Code, Codex and Pi. [repo](https://github.com/AVGVSTVS96/prompt-picker)",
      "- sources and filters are plugins in one `config.ts`, so any tool's history can be a source",
      "- `pk ls` gives agents the same data as plain text or JSONL",
      "- my prompt history is where this whole graph came from",
    ),

    page(
      "CRDTs",
      "alias:: CRDT",
      "tags:: local-first",
      "",
      "- every device edits its own copy, and merges always agree",
      `- why seqno needs one: ${ref(ids.loro)}`,
      "- Loro has the two structures an outliner needs: a movable tree, and rich text per node",
      "\t- moves are tree moves. two concurrent moves that would make a cycle can't",
      "\t- each block's text is its own text CRDT, so two people typing in one block merge by character",
      "- sync with no server:",
      `\t- {{embed ${ref(ids.oneWriter)}}}`,
      "- importing an op twice changes nothing, so a conflict copy from iCloud is harmless",
      "- read [[Martin Kleppmann]] on local-first, in [[reading]]",
    ),
    page(
      "motion design",
      "alias:: animation",
      "",
      "- feel matters as much as function",
      `- ${ref(ids.overshoot)}`,
      "- everything that moves should be interruptible. a slide reverses from where it is, it doesn't finish first",
      "- hover cards: 150 ms to open, then a 400 ms window where the next one opens instantly",
      "- TODO seqno's search palette and popups have no exit animation yet [[projects/seqno]]",
      "- read: [[Emil Kowalski]], and Apple's Designing Fluid Interfaces in [[reading]]",
    ),
    page(
      "dark mode",
      "- design both themes at once, not light first",
      "- blur needs different numbers per theme: dark 42% black at 8px, light 38% tint at 10px",
      "- a side-by-side is only fair with the same content and the same sidebar open on both sides",
      "- seqno's harness shoots 12 screens next to Logseq in both themes [[projects/seqno]]",
    ),
    page(
      "prompting",
      "- my prompt is the brief. a fresh agent gets it word for word, plus where the files are. no summary, no extra goals #rule",
      `- reword a few words before adding a rule: ${ref(ids.reword)}`,
      `- ${ref(ids.onlyNever)}`,
      "- small fast models for watching and wide searches, judgment stays with the big one. small models on max effort overthink",
      "- plain words. write so I can follow cold, I'm switching between a lot of projects",
    ),
    page(
      "open source",
      "- my projects are public from the first commit, MIT",
      "- every commit signed. if signing breaks, fix signing",
      "- scope and design come from maintainers: what they said, merged or turned down",
      "- a PR a maintainer can decide on in a minute",
      "\t- what it does",
      "\t  logseq.order-list-type:: number",
      "\t- the decisions it makes",
      "\t  logseq.order-list-type:: number",
      "\t- big screenshots",
      "\t  logseq.order-list-type:: number",
      "- when I cite an issue, say who wrote it: a maintainer or someone from outside",
      "- release candidates from big, widely used projects are fine to build on",
    ),
    page(
      "naming",
      "- names are lowercase. one word if it fits, two at most",
      "- search a name before getting attached to it",
      "- commonplace took four rounds, see the storm on " + date(-4),
    ),
    page(
      "reading",
      "- DONE [Local-first software](https://www.inkandswitch.com/local-first/)",
      "  author:: [[Martin Kleppmann]]",
      "  why:: the seven ideals. seqno is a bet on all of them",
      "- DONE [Loro: the movable tree](https://loro.dev/docs/tutorial/tree)",
      "  why:: why seqno didn't have to write its own tree CRDT",
      "- DONE [Effect v4 migration guide](https://github.com/Effect-TS/effect/blob/main/MIGRATION.md)",
      "  why:: Context.Service, Result instead of Either, the new Schema names",
      "- LATER [Designing Fluid Interfaces](https://developer.apple.com/videos/play/wwdc2018/803/), WWDC18",
      "  why:: interruptible motion, for the sidebar peek",
      "- LATER [animations.dev](https://animations.dev)",
      "  author:: [[Emil Kowalski]]",
      "- TODO [Logseq query docs](https://docs.logseq.com/#/page/queries)",
      "  why:: run every example through seqno",
      "- LATER [How Instinct's memory works](https://supermemory.ai/blog/reverse-engineering-instinct-memory/)",
      "  why:: ideas for hex's memory",
    ),
    page(
      "snippets",
      "- sign every commit with an SSH key",
      "\t- ```sh",
      "\t  git config --global gpg.format ssh",
      "\t  git config --global user.signingkey ~/.ssh/id_ed25519.pub",
      "\t  git config --global commit.gpgsign true",
      "\t  ```",
      "- launch videos: tag BT.709 or the colors wash out after upload",
      "\t- ```sh",
      "\t  ffmpeg -i in.mov -c:v libx264 -pix_fmt yuv420p \\",
      "\t    -colorspace bt709 -color_primaries bt709 -color_trc bt709 \\",
      "\t    out.mp4",
      "\t  ```",
      "- heavy commands in a memory-capped scope, so a runaway test can't take the box down",
      "\t- ```sh",
      "\t  systemd-run --user --scope -p MemoryMax=1500M -p MemorySwapMax=0 pnpm test",
      "\t  ```",
      "- is it public yet?",
      "\t- ```sh",
      "\t  gh repo view AVGVSTVS96/seqno --json visibility -q .visibility",
      "\t  ```",
      "- an Effect v4 service",
      "\t- ```ts",
      '\t  class Vault extends Context.Service<Vault, { readonly sync: Effect.Effect<void> }>()("Vault") {}',
      "\t  ```",
    ),
    page(
      "people",
      "- people whose work I keep going back to",
      "- {{query (page-property type person)}}",
    ),
    page(
      "Martin Kleppmann",
      "type:: [[person]]",
      "",
      "- local-first, CRDTs, Designing Data-Intensive Applications. [site](https://martin.kleppmann.com)",
    ),
    page(
      "Emil Kowalski",
      "type:: [[person]]",
      "",
      "- web animation and interaction feel. [site](https://emilkowal.ski)",
    ),
    page(
      "Theo Browne",
      "type:: [[person]]",
      "",
      "- T3 Code. found react-shiki early. [site](https://t3.gg)",
    ),
    page(
      "Wes Billman",
      "type:: [[person]]",
      "",
      "- Buzz. the cursor-shy bees on its opening screen. [github](https://github.com/wesbillman)",
    ),
  ]
}
