import { EditorView } from "@codemirror/view"

const heading = (size: string, leading: string, rule: string | null) => ({
  ...(rule === null
    ? {}
    : {
        marginBlock: rule,
        paddingBottom: rule,
        borderBottom: "1px solid var(--border-heading)",
      }),
  "& .cm-content": {
    fontSize: size,
    lineHeight: leading,
    fontWeight: "var(--weight-semibold)",
  },
})

const enter = (lift: string) => ({
  from: { opacity: "0", transform: `translateY(${lift}) scale(0.95)` },
})

const row = {
  display: "flex",
  boxSizing: "border-box",
  minHeight: "32px",
  padding: "var(--space-1-5) var(--space-2)",
  borderRadius: "var(--radius-sm)",
  fontSize: "var(--text-sm)",
  lineHeight: "var(--leading-sm)",
  color: "var(--fg-popup)",
  cursor: "pointer",
  transition: "opacity var(--duration-base) var(--ease-standard)",
}

export const editorTheme = EditorView.theme({
  "&": {
    color: "inherit",
    backgroundColor: "transparent",
    font: "inherit",
  },
  "&.cm-focused": { outline: "none" },
  ".cm-scroller": {
    fontFamily: "inherit",
    lineHeight: "inherit",
    overflow: "visible",
  },
  ".cm-content": {
    padding: "0",
    minHeight: "var(--leading-base)",
    caretColor: "var(--fg)",
  },
  ".cm-line": { padding: "0" },
  "&.sq-h1": heading("var(--text-h1)", "var(--leading-h1)", "var(--space-1)"),
  "&.sq-h2": heading("var(--text-h2)", "var(--leading-h2)", "3px"),
  "&.sq-h3": heading("var(--text-h3)", "var(--leading-h3)", null),
  "&.sq-h4, &.sq-h5, &.sq-h6": heading("var(--text-base)", "var(--leading-base)", null),

  ".cm-tooltip.sq-popup-host": {
    border: "none",
    backgroundColor: "transparent",
    display: "flex",
    flexDirection: "column",
    maxHeight: "min(600px, var(--popup-room, 600px))",
  },
  ".cm-tooltip.sq-popup-host:has(> .sq-popup-slash)": {
    maxHeight: "min(480px, var(--popup-room, 480px))",
  },
  "@keyframes sq-popup-below": enter("calc(-1 * var(--space-2))"),
  "@keyframes sq-popup-above": enter("var(--space-2)"),
  ".sq-popup": {
    boxSizing: "border-box",
    width: "512px",
    maxWidth: "100vw",
    minHeight: "0",
    overflowY: "auto",
    padding: "var(--space-1-5)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-md)",
    backgroundColor: "var(--bg-popover)",
    boxShadow: "var(--shadow-popover)",
    color: "var(--fg-strong)",
    fontFamily: "var(--font-sans)",
    fontSize: "var(--text-base)",
    lineHeight: "var(--leading-base)",
    transformOrigin: "top left",
    animation: "sq-popup-below var(--duration-base) ease",
  },
  ".cm-tooltip-above .sq-popup": {
    transformOrigin: "bottom left",
    animationName: "sq-popup-above",
  },
  ".sq-popup::-webkit-scrollbar": { display: "none" },
  ".sq-popup.sq-popup-slash": { width: "288px" },
  ".sq-popup-group": {
    boxSizing: "border-box",
    height: "32px",
    padding: "var(--space-2)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--leading-xs)",
    fontWeight: "var(--weight-medium)",
    color: "var(--fg-popup-group)",
  },
  ".sq-popup-row": row,
  ".sq-popup-row:hover": { color: "var(--fg-strong)" },
  ".sq-popup-row[aria-selected=true]": { backgroundColor: "var(--bg-popup-active)" },
  ".sq-popup-command": {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-1)",
    minWidth: "0",
  },
  ".sq-popup-command-icon": {
    display: "flex",
    flex: "none",
    marginRight: "1px",
    opacity: "var(--opacity-popup-icon)",
  },
  ".sq-popup-row[aria-selected=true] .sq-popup-command-icon": { opacity: "1" },
  ".sq-popup-entry": { display: "flex", alignItems: "flex-start", minWidth: "0" },
  ".sq-popup-icon": {
    display: "flex",
    flex: "none",
    alignItems: "center",
    height: "var(--leading-sm)",
    marginRight: "var(--space-1)",
    opacity: "0.5",
  },
  ".sq-popup-block": { display: "flex", flexDirection: "column", minWidth: "0", flex: "1" },
  ".sq-popup-crumb": {
    margin: "0 0 var(--space-1) 3px",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--leading-xs)",
    opacity: "0.7",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  ".sq-popup-text": { overflowWrap: "anywhere" },
  ".cm-tooltip.sq-date-host": { border: "none", backgroundColor: "transparent" },
  ".sq-date": {
    "--fg-date-month": "light-dark(#0f1419, #93a1a1)",
    "--fg-date-weekday": "light-dark(#333333, #a4b5b6)",
    "--fg-date-off": "light-dark(#999999, #666666)",
    "--bg-date-hover": "light-dark(#dbdbdb, #3e3e3e)",
    "--bg-date-active": "rgb(3 125 186 / 0.9)",
    "--bg-date-select": "light-dark(#f3f3f3, #023643)",
    "--border-date-input": "light-dark(#dbdbdb, #004152)",
    display: "flex",
    boxSizing: "border-box",
    width: "511px",
    maxWidth: "100vw",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)",
    backgroundColor: "var(--bg-popover)",
    boxShadow: "var(--shadow-dialog)",
    color: "var(--fg)",
    fontFamily: "var(--font-sans)",
    fontSize: "var(--text-base)",
    lineHeight: "var(--leading-base)",
    animation: "sq-popup-below var(--duration-base) ease",
  },
  ".sq-date-calendar": { flex: "none", boxSizing: "border-box", width: "209px", padding: "10px" },
  ".sq-date table": {
    width: "189px",
    borderCollapse: "collapse",
    fontSize: "13px",
    lineHeight: "16px",
    userSelect: "none",
  },
  ".sq-date th, .sq-date td": {
    boxSizing: "border-box",
    width: "27px",
    height: "26px",
    padding: "0",
    fontWeight: "var(--weight-regular)",
    textAlign: "center",
  },
  ".sq-date-turn": {
    width: "100%",
    height: "100%",
    padding: "0",
    border: "0",
    background: "none",
    color: "var(--ring-color)",
    font: "inherit",
    cursor: "pointer",
  },
  ".sq-date-month": { color: "var(--fg-date-month)", fontSize: "var(--text-sm)" },
  ".sq-date-weekday": { color: "var(--fg-date-weekday)", fontSize: "10px" },
  ".sq-date-day": {
    border: "1px solid transparent",
    borderRadius: "var(--radius-sm)",
    cursor: "pointer",
  },
  ".sq-date-day:hover": { backgroundColor: "var(--bg-date-hover)" },
  ".sq-date-day[data-off]": { color: "var(--fg-date-off)" },
  ".sq-date-day[aria-selected=true]": {
    borderColor: "var(--ring-color)",
    backgroundColor: "var(--bg-date-active)",
    color: "#ffffff",
  },
  ".sq-date-options": {
    flex: "none",
    boxSizing: "border-box",
    width: "300px",
    padding: "var(--space-1) var(--space-4)",
  },
  ".sq-date-label": {
    margin: "var(--space-4) 0 var(--space-2)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--leading-sm)",
    fontWeight: "var(--weight-medium)",
    color: "var(--fg-control)",
    opacity: "0.5",
  },
  ".sq-date-add": {
    display: "block",
    height: "17px",
    padding: "0",
    border: "0",
    background: "none",
    color: "var(--fg-link)",
    fontFamily: "inherit",
    fontSize: "var(--text-sm)",
    lineHeight: "17px",
    cursor: "pointer",
  },
  ".sq-date-row": { display: "flex", alignItems: "center", gap: "var(--space-2)" },
  ".sq-date-input": {
    boxSizing: "border-box",
    padding: "var(--space-2)",
    border: "1px solid var(--border-date-input)",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "var(--bg-popover)",
    color: "var(--fg)",
    fontFamily: "inherit",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--leading-sm)",
  },
  ".sq-date-input:focus": { outline: "none", boxShadow: "var(--ring)" },
  ".sq-date-time": { width: "236px", height: "32px", paddingRight: "var(--space-3)" },
  ".sq-date-count": { width: "80px", height: "38px", textAlign: "center" },
  ".sq-date-select": { position: "relative", display: "flex" },
  ".sq-date-select > svg": {
    position: "absolute",
    top: "10px",
    right: "var(--space-3)",
    pointerEvents: "none",
  },
  ".sq-date-unit": {
    width: "148px",
    height: "38px",
    padding: "var(--space-2) 40px var(--space-2) var(--space-3)",
    appearance: "none",
    backgroundColor: "var(--bg-date-select)",
    fontSize: "var(--text-base)",
    lineHeight: "var(--leading-base)",
  },
  ".sq-date-remove": {
    display: "flex",
    padding: "2px",
    border: "0",
    background: "none",
    color: "var(--fg-link)",
    cursor: "pointer",
  },
  ".sq-date-submit": { margin: "var(--space-4) 0 var(--space-2)" },
  ".sq-date-button": {
    height: "28px",
    padding: "var(--space-1) var(--space-3)",
    border: "0",
    borderRadius: "var(--radius-sm)",
    backgroundColor: "var(--bg-date-active)",
    boxShadow: "inset 0 1px 0 0 rgb(255 255 255 / 0.15)",
    color: "#ffffff",
    fontFamily: "inherit",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--leading-sm)",
    fontWeight: "var(--weight-medium)",
    cursor: "pointer",
  },
  ".sq-date-button:hover": { backgroundColor: "var(--ring-color)" },
  ".sq-popup mark": {
    padding: "0",
    borderRadius: "0",
    backgroundColor: "var(--bg-mark)",
    color: "var(--fg-mark)",
  },
})
