import type { StarterFile } from "../place.ts"
import type { Days } from "./kit.ts"
import { dated, ids, page, ref } from "./kit.ts"

const person = (name: string, ...lines: ReadonlyArray<string>) =>
  page(name, "type:: [[person]]", "", ...lines)

export const hub = (d: Days): ReadonlyArray<StarterFile> => [
  page(
    "Contents",
    "- [[About this graph]]",
    "- [[review]]: open tasks, decisions, what's due",
    "- **projects**",
    "\t- now: [[projects/seqno]] · [[projects/hex]] · [[projects/commonplace]] · [[projects/brand-it]]",
    "\t- libraries and tools: [[projects/react-shiki]] · [[projects/prompt-picker]] · [[projects/better-github-skill]] · [[projects/PATCH.md]] · [[projects/vim-herdr-navigator]] · [[projects/persistence-scope.nvim]] · [[projects/codexbar]] · [[projects/astro-fouc-killer]]",
    "\t- before: [[projects/portfolio]] · [[projects/fastgpt]] · [[projects/openleaf]] · [[projects/dotfiles]]",
    "\t- every project page lists its decisions, and why",
    "- **topics**",
    "\t- code: [[CRDTs]] · [[motion design]] · [[dark mode]] · [[design]] · [[prompting]] · [[open source]] · [[terminal]] · [[notes apps]] · [[naming]]",
    "\t- the rest: [[history]] · [[Rome]] · [[systems of power]] · [[philosophy]] · [[sci-fi]] · [[keyboards]] · [[making things]] · [[racing]] · [[SF]]",
    "- [[learning to code]] · [[watching]] · [[reading]] · [[snippets]] · [[people]]",
    "- **on it now**",
    "\t- {{query (task NOW DOING)}}",
  ),
  page(
    "About this graph",
    "author:: [[Bassim Shahidy]]",
    "",
    "- My demo graph. It starts in January 2023, the month I started learning to code, and gets denser the closer it gets to today.",
    "- This is a typical developer's Logseq graph. It shows how a developer can still get value from notes in the age of AI, when most of what we type goes to agents.",
    "- Some people take a lot more notes than others. My circle are developers who put most of their text into prompts, and this is for them. I don't take notes myself, so I went back through my prompts, my posts, my commits and my watch history, and kept what I'd want written down:",
    "\t- decisions and why: [[decision]]",
    "\t- rules I learned the hard way: [[rule]]",
    "\t- bugs worth remembering: [[bug]]",
    "\t- ideas for later, and a line or two a day in the journals",
    "\t- the videos and books that stuck, and the history, sci-fi and keyboards that have nothing to do with code",
    "- The part I like most: every project page lists the decisions that went into it.",
    "- The agents write the code, the docs and the commit messages. This is the place I write.",
    "- Start with Contents in the right sidebar (`t r`), or the [[review]] page.",
    "- Bassim",
  ),
  page(
    "review",
    "alias:: dashboard",
    "",
    "- TODO weekly review",
    `  SCHEDULED: ${d.stamp(2, " .+1w")}`,
    "- ## open tasks",
    "\t- {{query (task NOW DOING TODO)}}",
    "- ## due in the next two weeks",
    "\t- {{query (and (task NOW DOING TODO) (task.deadline <= +14d))}}",
    "- ## decisions, last two weeks",
    "\t- {{query (and [[decision]] (between -14d today))}}",
    "- ## every decision",
    "  collapsed:: true",
    "\t- {{query [[decision]]}}",
    "- ## rules",
    "  collapsed:: true",
    "\t- {{query [[rule]]}}",
    "- ## later",
    "\t- {{query (task LATER)}}",
    "- ## weeks",
    "\t- {{query [[weekly]]}}",
  ),
  page(
    "reading",
    "- DONE [Local-first software](https://www.inkandswitch.com/local-first/)",
    "  author:: [[Martin Kleppmann]]",
    "  why:: the seven ideals. seqno is a bet on all of them",
    "- DONE [Loro: the movable tree](https://loro.dev/docs/tutorial/tree)",
    "  why:: why seqno didn't have to write its own tree CRDT",
    "- DONE [Effect v4 migration guide](https://github.com/Effect-TS/effect/blob/main/MIGRATION.md)",
    "  why:: Context.Service, Result instead of Either, the new Schema names",
    "- LATER [Designing Fluid Interfaces](https://developer.apple.com/videos/play/wwdc2018/803/), WWDC18",
    "  why:: interruptible motion, for the sidebar peek",
    "- LATER [animations.dev](https://animations.dev)",
    "  author:: [[Emil Kowalski]]",
    "- TODO [Logseq query docs](https://docs.logseq.com/#/page/queries)",
    "  why:: run every example through seqno",
    "- LATER [How Instinct's memory works](https://supermemory.ai/blog/reverse-engineering-instinct-memory/)",
    "  why:: ideas for hex's memory",
    "- DONE The Three-Body Problem trilogy, Cixin Liu [[sci-fi]]",
    `  why:: found it through [[Quinn's Ideas]], ${dated(20220528)}`,
    "- There Is No Antimemetics Division, qntm [[sci-fi]]",
    `\t- ${ref(ids.antimemetics)}`,
    "- Corruptible: Who Gets Power and How It Changes Us, the audiobook [[systems of power]]",
    "  author:: [[Brian Klaas]]",
    `\t- ${ref(ids.corruptible)}`,
    "\t- related: [Revisiting the Stanford Prison Experiment](https://pubmed.ncbi.nlm.nih.gov/17440210/), Carnahan & McFarland, 2007",
  ),
  page(
    "snippets",
    "- sign every commit with an SSH key",
    "\t- ```sh",
    "\t  git config --global gpg.format ssh",
    "\t  git config --global user.signingkey ~/.ssh/id_ed25519.pub",
    "\t  git config --global commit.gpgsign true",
    "\t  ```",
    "- launch videos: tag BT.709 or the colors wash out after upload",
    "\t- ```sh",
    "\t  ffmpeg -i in.mov -c:v libx264 -pix_fmt yuv420p \\",
    "\t    -colorspace bt709 -color_primaries bt709 -color_trc bt709 \\",
    "\t    out.mp4",
    "\t  ```",
    "- heavy commands in a memory-capped scope, so a runaway test can't take the box down",
    "\t- ```sh",
    "\t  systemd-run --user --scope -p MemoryMax=1500M -p MemorySwapMax=0 pnpm test",
    "\t  ```",
    "- is it public yet?",
    "\t- ```sh",
    "\t  gh repo view AVGVSTVS96/seqno --json visibility -q .visibility",
    "\t  ```",
    "- an Effect v4 service",
    "\t- ```ts",
    '\t  class Vault extends Context.Service<Vault, { readonly sync: Effect.Effect<void> }>()("Vault") {}',
    "\t  ```",
    "- one nvim socket per tmux pane",
    "\t- ```sh",
    '\t  nvim --listen /tmp/nvim-$(tmux display-message -p "#S-#I-#P")',
    "\t  ```",
  ),
  page(
    "people",
    "- people whose work I keep going back to",
    "- {{query (page-property type person)}}",
  ),
  person(
    "Martin Kleppmann",
    "- local-first, CRDTs, Designing Data-Intensive Applications. [site](https://martin.kleppmann.com)",
  ),
  person("Emil Kowalski", "- web animation and interaction feel. [site](https://emilkowal.ski)"),
  person(
    "Theo Browne",
    "- T3 Code. found react-shiki early. [site](https://t3.gg)",
    "- his videos, most days since January 2024. a big part of why I'm the engineer I am",
    `\t- ${d.date(-24)}`,
  ),
  person(
    "Wes Billman",
    "- Buzz. the cursor-shy bees on its opening screen. [github](https://github.com/wesbillman)",
  ),
  person(
    "ThePrimeagen",
    "- vim, hot takes, The PrimeTime. [youtube](https://www.youtube.com/@ThePrimeagen)",
    `- one of the first dev channels I watched, three weeks into CS50: ${dated(20230130)}`,
  ),
  person(
    "exurb1a",
    "- philosophy, space and dread, with jokes. [youtube](https://www.youtube.com/@exurb1a)",
    "- watching since 2018",
    `- ${dated(20260509)}: this is what exurb1a is really about`,
  ),
  person(
    "Historia Civilis",
    "- Roman history with little squares, and essays like Work. and The City. [youtube](https://www.youtube.com/@HistoriaCivilis)",
    "- watching since 2019",
  ),
  person(
    "Jacob Geller",
    "- video essays about games, art and memory. [youtube](https://www.youtube.com/@JacobGeller)",
    "- I love his essays. always want to mention them",
  ),
  person(
    "Quinn's Ideas",
    "- sci-fi books, explained and argued about. [youtube](https://www.youtube.com/@QuinnsIdeas)",
    `- how I found the Three-Body books: ${dated(20220528)}`,
  ),
  person(
    "CGP Grey",
    "- explainers. Rules for Rulers, and the rest. [youtube](https://www.youtube.com/@CGPGrey)",
  ),
  person(
    "Brian Klaas",
    "- political scientist. wrote Corruptible: Who Gets Power and How It Changes Us",
  ),
  person(
    "Anthony Fu",
    "- Shiki, among a lot of other things. react-shiki stands on his work. [github](https://github.com/antfu)",
  ),
  person(
    "Ryan Norbauer",
    `- makes keyboards. [Forgotten Futures](https://www.youtube.com/watch?v=EYGoXXNhj4U), on what makes them magic: ${dated(20230407)}`,
  ),
]
