import type { StarterFile } from "../place.ts"
import type { Days } from "./kit.ts"
import { dated, ids, page, ref } from "./kit.ts"

const decisions = (alias: string) => [
  "- ## decisions",
  `\t- {{query (and [[decision]] [[${alias}]])}}`,
]

export const projects = (d: Days): ReadonlyArray<StarterFile> => [
  page(
    "projects/seqno",
    "alias:: seqno",
    "type:: [[project]]",
    "status:: hardening",
    "tags:: local-first, outliner",
    `started:: ${d.date(-16)}`,
    "",
    "- Logseq, rebuilt local-first on Loro, SQLite and Effect. web first, then iOS and desktop",
    "\t- [repo](https://github.com/AVGVSTVS96/seqno) · [app](https://seqno-app.vercel.app) · [site](https://seqno.vercel.app)",
    `- I was comparing Obsidian and Logseq two months into teaching myself to code: ${ref(ids.logseqHole)}`,
    ...decisions("seqno"),
    "- ## open",
    "\t- TODO [#A] peer ids get reused when some update files aren't downloaded yet. devices then disagree for good, silently",
    `\t  DEADLINE: ${d.stamp(5)}`,
    "\t- TODO [#A] two devices both create today's journal before syncing: two pages, one name, graph won't open",
    "\t- TODO [#B] check in a 50k-block benchmark that fails when open or typing goes over budget",
    `\t  SCHEDULED: ${d.stamp(1)}`,
    "\t- LATER turn on the markdown mirror so Logseq sees seqno's edits",
    "- ## hardening, in order",
    "\t- open lazily: newest snapshot, visible page first, index kept on disk",
    "\t  logseq.order-list-type:: number",
    "\t- close the data-safety gaps, peer ids and duplicate names first",
    "\t  logseq.order-list-type:: number",
    "\t- keep the edit log small on one device, and show save state",
    "\t  logseq.order-list-type:: number",
    "\t- markdown mirror on",
    "\t  logseq.order-list-type:: number",
    "\t- sync sim on the real graph, then the full 1,000 runs of 10k ops",
    "\t  logseq.order-list-type:: number",
    "- ## numbers",
    "\t- {{embed [[projects/seqno/numbers]]}}",
    "- ## open question",
    "\t- lazy open vs backlinks: a page's references need the index, and the index needs every page. what loads first? #question",
    "- homepage hero follows Buzz's opening screen. credited to [[Wes Billman]] in the README",
    `- desktop is Electron. I've been saying Electron is underrated since ${dated(20250928)}`,
  ),
  page(
    "projects/seqno/numbers",
    "- 50k blocks on 1,865 pages, headless Chrome and the iOS simulator",
    "- full open: 1,181 ms web, 2,435 ms iOS",
    "- page list + first page: 388 ms web, 178 ms iOS",
    "- keystroke p95: 0.14 ms web, 0.053 ms iOS",
    "- merge 1k remote edits, warm: 48.9 ms web, 57.6 ms iOS",
    "- slowest of 15 real queries, p95: 12.9 ms",
    '- loro-ffi at opt-level 3 instead of "z": 2-6x faster for ~2 MB more app',
  ),
  page(
    "projects/hex",
    "alias:: hex",
    "type:: [[project]]",
    "status:: alpha",
    "tags:: assistant, claude-code",
    `started:: ${d.date(-22)}`,
    "",
    "- a personal assistant that lives in your Telegram, built on Claude Code. [repo](https://github.com/AVGVSTVS96/hex)",
    "- how it should behave",
    "\t- it just works. that's the whole feature",
    "\t- behavior follows real events: hooks, signals, status. never a timer standing in for one",
    "\t- anything built for hex keeps working with stock Claude Code",
    ...decisions("hex"),
    "- the rule I keep relearning:",
    `\t- {{embed ${ref(ids.onlyNever)}}}`,
    "- TODO DMs get their own session on every connector, not forwarded into the main thread",
    "- TODO [#B] a false safety flag recovers by itself: same model, reworded, work kept. tell me only after a few in a row",
    "- LATER pick effort and model per thread, from any chat",
  ),
  page(
    "projects/commonplace",
    "alias:: commonplace",
    "type:: [[project]]",
    "status:: v0.1",
    "stack:: Bun, bun:sqlite, plain TypeScript",
    `started:: ${d.date(-4)}`,
    "",
    "- your personal data kit for agents. [repo](https://github.com/AVGVSTVS96/commonplace)",
    "- all of it, not just GitHub: texts, mail, saves, watch history, charges. that's how an agent learns your intent and judgment",
    ...decisions("commonplace"),
    "- redact at import, not at read. what never gets in can't leak #decision #commonplace",
    "- the README sorts sources: built in, one setup step away, coming. people should see what works today",
    "- brand: paper `#FAF9F6`, one red `#D2451E`, Ioskeley Mono (Iosevka shaped like Berkeley Mono, OFL)",
    `- watched "You should start a commonplace book today" six months before, on ${dated(20260421)}`,
    "- TODO live X source through the official API, pay per use. no scraping",
    "- LATER docs pages",
  ),
  page(
    "projects/brand-it",
    "type:: [[project]]",
    "status:: shipped",
    `started:: ${d.date(-3)}`,
    "",
    "- a skill for coding agents: brand a project from its own parts, all built as code",
    "\t- [repo](https://github.com/AVGVSTVS96/brand-it) · [site](https://brand-it-seven.vercel.app)",
    "- name, wordmark, palette, type, site, link preview, README header, launch post, launch video",
    "- the brand comes from the product's own parts, not a mood board",
    "- every page checked at every width, light and dark, before it's done [[dark mode]]",
    "- TODO social preview image still needs a manual upload on GitHub",
  ),
  page(
    "projects/react-shiki",
    "alias:: react-shiki",
    "type:: [[project]]",
    "status:: maintained",
    "tags:: syntax highlighting",
    `started:: ${dated(20240801)}`,
    "",
    "- syntax highlighting hook and component for React, powered by [Shiki](https://shiki.style). [repo](https://github.com/AVGVSTVS96/react-shiki) · [docs](https://react-shiki.vercel.app)",
    '- > "one of the best implementations of syntax highlighting i\'ve ever seen in react" --[[Theo Browne]]',
    "- 536 stars",
    `- next: ${ref(ids.cache)}`,
    "- how it got here",
    `\t- a chat page on my site needed code blocks. Prism first, then Shiki: ${dated(20240626)}`,
    `\t- its own package: ${dated(20240801)}`,
    `\t- Theo found it with 5 stars: ${dated(20250222)}`,
    `\t- one CSS problem, three tries: a renamed layer, then no layer, then CSS that installs itself. ${ref(ids.whereStyles)}`,
    ...decisions("react-shiki"),
    "- built on [[Anthony Fu]]'s Shiki",
  ),
  page(
    "projects/prompt-picker",
    "alias:: prompt-picker",
    "type:: [[project]]",
    "status:: maintained",
    "",
    "- a TUI and CLI to search every prompt I've sent to Claude Code, Codex and Pi. [repo](https://github.com/AVGVSTVS96/prompt-picker)",
    "- sources and filters are plugins in one `config.ts`, so any tool's history can be a source",
    "- `pk ls` gives agents the same data as plain text or JSONL",
    "- my prompt history is where this whole graph came from",
    ...decisions("prompt-picker"),
  ),
  page(
    "projects/portfolio",
    "alias:: portfolio",
    "type:: [[project]]",
    "status:: maintained",
    "tags:: astro, tailwind",
    `started:: ${dated(20230606)}`,
    "",
    "- my site, and where I try things first. [repo](https://github.com/AVGVSTVS96/astroSite) · [bassim.build](https://bassim.build)",
    "- v2 was Flask and Tailwind, March 2023. v3 is Astro, June 2023, my first multi-page app",
    "- still the same site I built when I first learned to code. I need to rebuild it",
    "- what grew out of it",
    "\t- [[projects/react-shiki]], from the chat page's code blocks",
    "\t- [[projects/astro-fouc-killer]], from the dark mode flash",
    "\t- a published remark-sectionize fork, for the table of contents",
    ...decisions("portfolio"),
  ),
  page(
    "projects/fastgpt",
    "alias:: fastgpt",
    "type:: [[project]]",
    `started:: ${dated(20230519)}`,
    "",
    "- the GPT chat app I built three ways in spring 2023, while learning",
    "\t- [FlaskGPT](https://github.com/AVGVSTVS96/flaskgpt): Flask and plain HTML, CSS and JS",
    "\t- [FastGPT](https://github.com/AVGVSTVS96/FastGPT): FastAPI, async requests, streaming",
    "\t- [reactGPT](https://github.com/AVGVSTVS96/reactgpt): FastAPI with a React frontend",
    "- my first real PRs, a GitHub Action, syntax highlighting, an autoscroll hook",
    ...decisions("fastgpt"),
  ),
  page(
    "projects/astro-fouc-killer",
    "alias:: astro-fouc-killer",
    "type:: [[project]]",
    `started:: ${dated(20240720)}`,
    "",
    "- an Astro integration that stops the dark mode flash on load. class-based dark mode in local storage, follows the system setting. [repo](https://github.com/AVGVSTVS96/astro-fouc-killer)",
    "- came out of [[projects/portfolio]]",
    ...decisions("astro-fouc-killer"),
  ),
  page(
    "projects/openleaf",
    "alias:: openleaf",
    "type:: [[project]]",
    `started:: ${dated(20251224)}`,
    "",
    "- minimal, end-to-end encrypted markdown notes. [repo](https://github.com/AVGVSTVS96/openleaf)",
    "- Astro, React 19, Tailwind 4, then Convex",
    ...decisions("openleaf"),
  ),
  page(
    "projects/dotfiles",
    "alias:: dotfiles",
    "type:: [[project]]",
    "status:: maintained",
    "",
    "- how my machines are set up, and how that changed",
    `\t- NixOS and nix-darwin, Sep 2024 → 2025. [nixos-config](https://github.com/AVGVSTVS96/nixos-config)`,
    `\t- GNU Stow and sops since ${dated(20260118)}`,
    "\t- neovim on LazyVim, its own repo. [neovim-config](https://github.com/AVGVSTVS96/neovim-config)",
    `\t- [starter-dotfiles](https://github.com/AVGVSTVS96/starter-dotfiles): the agent-managed version I made for a friend`,
    ...decisions("dotfiles"),
    "- [[terminal]]",
  ),
  page(
    "projects/vim-herdr-navigator",
    "alias:: vim-herdr-navigator",
    "type:: [[project]]",
    "status:: maintained",
    `started:: ${dated(20260702)}`,
    "",
    "- seamless navigation between herdr panes and vim/nvim splits. [repo](https://github.com/AVGVSTVS96/vim-herdr-navigator)",
    ...decisions("vim-herdr-navigator"),
    "- [[terminal]]",
  ),
  page(
    "projects/PATCH.md",
    "alias:: patch-md",
    "type:: [[project]]",
    "status:: v0.1",
    `started:: ${dated(20260624)}`,
    "",
    "- agent-healable source patches in markdown. [spec](https://github.com/AVGVSTVS96/patch_md-spec)",
    `- ${ref(ids.patchFormat)}`,
    "- where it runs",
    "\t- [herdr fork](https://github.com/AVGVSTVS96/herdr): CI cuts patched herdr releases from PATCH.md specs, agents re-heal the patches when upstream moves",
    "\t- [pi-patcher](https://github.com/AVGVSTVS96/pi-patcher): the same for the pi coding agent",
    "\t- my buzz fork's nightly",
    ...decisions("patch-md"),
    "- [[open source]]",
  ),
  page(
    "projects/better-github-skill",
    "alias:: better-github-skill",
    "type:: [[project]]",
    "status:: maintained",
    `started:: ${dated(20260811)}`,
    "",
    "- a GitHub skill for coding agents: fewer tool calls, less context, faster answers. one bounded call each for PR state, review threads and CI failures. [repo](https://github.com/AVGVSTVS96/better-github-skill)",
    ...decisions("better-github-skill"),
  ),
  page(
    "projects/persistence-scope.nvim",
    "alias:: persistence-scope",
    "type:: [[project]]",
    "status:: maintained",
    `started:: ${dated(20260518)}`,
    "",
    "- pluggable session scoping for folke's persistence.nvim. tmux by default, any scope through a provider. [repo](https://github.com/AVGVSTVS96/persistence-scope.nvim)",
    "- v0.2: one picker for everything, ranked recent → scope+cwd+branch → scope+cwd → scope → the rest",
    ...decisions("persistence-scope"),
    "- [[terminal]]",
  ),
  page(
    "projects/codexbar",
    "alias:: codexbar",
    "type:: [[project]]",
    `started:: ${dated(20260709)}`,
    "",
    "- a simplified, lightweight fork of steipete's CodexBar, the menu bar app for Claude and Codex usage. [repo](https://github.com/AVGVSTVS96/codexbar)",
    ...decisions("codexbar"),
  ),
  page(
    "learning to code",
    "- started January 2023, with CS50",
    `- the first months: ${dated(20230109)}, ${dated(20230315)}, ${dated(20230519)}`,
    `- never fell into tutorial hell. I built things and learned while doing. ${dated(20250929)}`,
    "- a lot of [[Theo Browne]], some [[ThePrimeagen]]",
    "- [[projects/fastgpt]] and [[projects/portfolio]] are where it happened",
  ),
]
