import type { StarterFile } from "../place.ts"
import type { Days } from "./kit.ts"
import { ids, post, ref } from "./kit.ts"

export const recent = (d: Days): ReadonlyArray<StarterFile> => [
  d.journal(
    0,
    "- NOW seqno lazy open, first step of hardening [[projects/seqno]]",
    "- 509 commits across 22 projects in 6 days. the 95 days before that: 580. the slow part is me reading now, not typing",
    "- week #weekly",
    "\t- shipped: [[projects/seqno]] web app, [[projects/commonplace]], [[projects/brand-it]]",
    "\t- next: seqno hardening, the react-shiki cache",
    "- too many projects open. the fix is a list I trust, not fewer ideas",
    "- every piece of hex is open source and works with or without hex #decision #hex",
    `\t- fully hackable, and still approachable for people who never open a terminal ${post("2108352926406283526")}`,
    `\t- as modular and flexible as I can make each piece ${post("2108353442746159410")}`,
    `- why do the labs keep "uh" and "um" in voice transcripts sent to the model? #question ${post("2108708396627320908")}`,
  ),
  d.journal(
    -1,
    "- scope comes from maintainers. an idea post nobody on the team answered isn't direction #rule [[open source]]",
    "- read the primary source myself. a summary of a summary ranked the wrong features first #rule",
    "\t- and before ranking anything, check what people actually get excited about",
    `- using the project I'm building to build itself ${post("2107998995121652019")}`,
    `- posted the Logseq side by side. I used to like Logseq, it got buggy and unreliable, so my agent rebuilt it on a proper stack, Effect v4 included [[projects/seqno]] ${post("2108158851669488052")}`,
    "\t- ![Logseq and seqno, side by side](https://pbs.twimg.com/media/HUGvTZ2awAAe3J6.jpg)",
    `\t- where it started, in 2023: ${ref(ids.logseqHole)}`,
    `- 34 projects started in 60 hours ${post("2108161052395622654")}`,
    `- my whole history in one place for my agents: every post, prompt, review comment and commit. they mirror my judgment closer than anything else [[projects/commonplace]] ${post("2108244948554526784")}`,
    "- hex stays ~1,000 lines #decision #hex",
    `\t- elegant simplicity without a single sacrifice. a hackable community test bed ${post("2108251903490666920")}`,
    `\t- memory on OptMem ${post("2108250265111663025")}`,
    "\t- clients at launch: Telegram, Discord, Buzz, T3 Code",
  ),
  d.journal(
    -2,
    "- sidebar idea: a compact rail, plus a hover peek from the left edge [[motion design]]",
    "\t- I move fast and overshoot the edge. ==open slow, close slower==",
    `\t  id:: ${ids.overshoot}`,
    "\t- what felt right: 6px edge strip, 100 ms dwell to open, 200 ms grace after leaving, a 240 ms slide that can reverse halfway",
    "- destructive buttons: arm inline instead of a modal. the button grows, turns orange, second click deletes #idea",
    `- I speak software into existence ${post("2107634840497709429")}`,
    `- Theo's framing: OpenAI is run by engineers, Anthropic by researchers. you can see it in how the two model families behave [[Theo Browne]] ${post("2107641647412793493", "98 likes")}`,
  ),
  d.journal(
    -3,
    "- [[projects/brand-it]]: a skill that brands a project from its own parts. then branded brand-it with it",
    "- launch video looked washed out once uploaded. it was missing the BT.709 color tags #bug",
    "\t- the ffmpeg line is in [[snippets]]",
    '- commonplace hero was six lines next to the terminal. now: "Everything you\'ve made, saved and said."',
    "\t- copy lives in one file. change it there first, then the site",
    "- hex wraps Claude Code #decision #hex",
    `\t- it runs on my Claude Max subscription, and I couldn't give that usage up ${post("2107443306913550639")}`,
    "- hex's main session rolls over every 24 hours #decision #hex",
    "\t- every user and assistant message goes to a log. each day starts a fresh session that reads the raw log or the merged memory",
    `\t- the chat still shows yesterday's messages ${post("2107271224997105978")}`,
    `- idea: a bot for repos that rarely merge outside PRs. it keeps up with upstream and merges the good contributor PRs the maintainers never got to #idea [[open source]] ${post("2107407763211260404")}`,
    "- an always-on agent on the server that stops a runaway process before it takes the box down #idea",
    `\t- today an agent killed a process in another thread that would have crashed T3 Code on the server ${post("2107429529514025268")}`,
  ),
  d.journal(
    -4,
    "- started [[projects/commonplace]]: all your data in one place, one door for every agent",
    "- agents don't get raw sqlite3. the CLI is the only door, with an MCP subcommand #decision #commonplace",
    `  id:: ${ids.oneDoor}`,
    "\t- the db is sensitive, and a remote agent can't reach a local socket anyway",
    "- name storm [[naming]]",
    "  collapsed:: true",
    "\t- ~~attic~~ too dusty",
    "\t- ~~annals~~ won't work",
    "\t- ~~chronicle~~ taken twice already",
    "\t- canon is a curated slice. this is everything",
    "\t- commonplace: a commonplace book for the age of agents",
    "- DONE commonplace v0.1 public. template repo + Claude Code plugin",
    `- being opinionated as a developer matters more than ever ${post("2107099955425108277")}`,
    `- Buzz is so well crafted. surprised more people don't talk about it ${post("2107070749110567175")}`,
    `- assistant sessions, the sweet spot: one main session, cleaned up and integrated daily, plus threads for units of work [[projects/hex]] ${post("2107108091473129653")}`,
  ),
  d.journal(
    -6,
    '- "only" and "never" don\'t belong in instruction files. each one needs a real reason, and there almost never is one #rule',
    `  id:: ${ids.onlyNever}`,
    "- a reply from hex went missing because a plugin prompt said to reply only in one case. same lesson",
    "- DOING go through every hex instruction file for only/never [[projects/hex]]",
  ),
  d.journal(
    -7,
    "- hex launch bar, written down so I stop moving it [[projects/hex]]",
    "\t- hackers self-host the alpha",
    "\t- someone's parents can use the hosted one within a day of launch",
    "- my prompts are instructions. anything I state should land in memory the moment I say it",
    "- week #weekly",
    "\t- shipped: hex to myself, seqno phase 0",
    "\t- next: seqno web app",
    `- Spear: a scrolling window manager for macOS, the closest thing to Niri I've seen. signed up for the beta [[terminal]] ${post("2106160572220006562", "539 likes")}`,
    `\t- what I want from a window manager: opening a window doesn't resize the others, and moving around the desktop is easy. horizontal scrolling gets both right ${post("2106154831518085487")}`,
  ),
  d.journal(
    -8,
    "- forks that maintain themselves: each patch is a short markdown spec, CI re-applies them on every upstream release #decision #patch-md",
    "\t- the [herdr fork](https://github.com/AVGVSTVS96/herdr) is the proof of concept",
    '- buzz fork "nightly" = the newest upstream main commit with green CI #decision #patch-md',
    "\t- upstream has no nightlies, so main is allowed to break",
    "- LATER package the fork bot so anyone can point it at any repo #idea",
  ),
  d.journal(
    -10,
    "- seqno web build. agents ran the phases, my part was reading the design harness: 12 screens next to Logseq, light and dark [[dark mode]]",
    "- flows find things by role, not CSS class. same hooks a screen reader uses",
    "- TODO make e2e fail on errors inside the core worker too, not only page errors [[projects/seqno]]",
  ),
  d.journal(
    -11,
    "- desktop = Electron #decision #seqno",
    "\t- same Chromium as the web build, so the web tests cover desktop. Tauri and Electrobun get Safari's engine on a Mac",
    "- SQLite is a cache: `journal_mode=memory`, `synchronous=off` #decision #seqno",
    "\t- the edit log can always rebuild it. 5.6 ms p95 per keystroke relaxed vs 14.1 ms durable",
    "- iCloud on iOS needs the paid developer program, and container ids can never be deleted. pick bundle and container ids once #rule",
  ),
  d.journal(
    -13,
    "- queries: Logseq syntax first, Dataview second #decision #seqno",
    "\t- dropped a third, Datalog-looking syntax. it looks like advanced queries but has no joins. wrong expectations",
    "\t- the same 15 real queries: 763 chars as Logseq, 975 as Dataview, 1,119 as Datalog",
    "- CANCELED Safari local-only mode. no writable folder picker means it never syncs. one less adapter to test",
  ),
  d.journal(
    -14,
    "- one writer per file in the synced folder. delete only after another device confirms the snapshot #decision #seqno",
    `  id:: ${ids.oneWriter}`,
    "\t- without the confirm step, 7 of 16 sim runs lost ops",
    "\t- with it: 1,000 runs, 0 lost ops",
    "- `tree.has(undefined)` crashes inside wasm and the doc is dead after. validate every id before it reaches Loro #bug",
    `- T3 Code: an open source alternative to Codex that benefits everyone. I've learned a lot from its code [[Theo Browne]] ${post("2103431646771097828")}`,
  ),
  d.journal(
    -16,
    "- [[projects/seqno]] phase 0: spikes before any app code. measure first",
    "- Loro is the source of truth, markdown is the mirror #decision #seqno",
    `  id:: ${ids.loro}`,
    "\t- markdown as truth = two devices editing one page write one file. the synced folder keeps one or makes a conflict copy. a CRDT merges both [[CRDTs]]",
    "\t- a keystroke: 0.14 ms on the web, 0.053 ms on iOS. ~100x under a frame",
    `- one good designer can carry a startup's whole brand. they should get paid a real premium over engineers ${post("2102817258246738342")} [[design]]`,
  ),
  d.journal(
    -18,
    "- one reworded line beat three new rules [[prompting]]",
    `  id:: ${ids.reword}`,
    '\t- before: "you can hand work off to subagents"',
    '\t- after: "you will often hand off work to keep your own context small"',
    "\t- same rule, but now it says when",
    `- become a data hoarder ${post("2101907981483090252")} [[projects/commonplace]]`,
  ),
  d.journal(
    -20,
    "- voice notes for hex: local Whisper took 27 s on a 50 s note. no",
    "- a newer 164 MB model does the same note in under 2 s, and it's more accurate. only found it because someone posted it #rule",
    "\t- never pick a model from memory. check what shipped this month",
    "- words it keeps mishearing: herdr, shadcn, tmux, TanStack, react-shiki. a dictionary file, not a longer prompt",
  ),
  d.journal(
    -22,
    "- started [[projects/hex]]. an assistant that lives in Telegram, built on Claude Code",
    "- build on the harness, not against it. Claude Code already did the hard part #rule",
    "- the whole thing should stay small enough to read in one sitting",
    `- every person's opinions make sense inside their own lived experience. before reacting with "wtf", get curious and ask why ${post("2100731406553071851")} [[philosophy]]`,
  ),
  d.journal(
    -25,
    "- every remount re-tokenizes on the main thread, so long chats re-highlight the same blocks over and over #bug [[projects/react-shiki]]",
    "\t- a cache should live in react-shiki, not in every app that uses it",
    "- TODO [#B] built-in highlight cache for react-shiki, keyed by code + lang + theme",
    `  id:: ${ids.cache}`,
    `  SCHEDULED: ${d.stamp(2)}`,
  ),
  d.journal(
    -27,
    "- react-shiki 0.11 out, just dependency bumps [[projects/react-shiki]]",
  ),

  d.journal(
    -24,
    `- Theo's videos are a big part of why I'm the engineer I am. learning from engineers of that caliber as a beginner was a privilege [[Theo Browne]] ${post("2099685765085356163", "94 likes")}`,
    "\t- Theo, Kent C. Dodds, and everyone whose videos, articles and open source code taught me [[learning to code]]",
    `- the Omarchy server comes online today. a stable Linux box for dev, and a homelab to tinker with [[terminal]] ${post("2099656477757915408")}`,
    `- split keyboards: my wrists would thank me, but they don't sound nearly as good. tried a Moonlander once, the blank keycaps didn't help [[keyboards]] ${post("2099669984016584705")}`,
    `- the purpose of creation is to fill the world with beauty, and there's beauty in the act itself. the care echoes out even when a copy gets the credit ${post("2099773324293472490")}`,
  ),
  d.journal(
    -21,
    `- so inspired I'm paralyzed by all the projects I want to do. still better than staring at a blank wall ${post("2100752079824507270")}`,
    "- parametric test print for fuzzy skin on the Bambu: thickness 0.2 and 0.5, point distance 0.1 to 0.6 [[making things]]",
  ),
  d.journal(
    -17,
    `- stopped using Aside's hover sidebar: overshoot the screen edge and it closes right after it opens ${post("2102192118349631858")} [[motion design]]`,
  ),
  d.journal(
    -5,
    `- don't get to talk about racing much on X. it's demanding, and rewarding [[racing]] ${post("2106656717216067980")}`,
  ),
]
