import type { StarterFile } from "../place.ts"
import type { Days } from "./kit.ts"
import { dated, ids, page, ref, thumb, video, yt } from "./kit.ts"

const bookmark = (title: string, id: string) => `[${title}](https://x.com/i/status/${id})`

export const topics = (d: Days): ReadonlyArray<StarterFile> => [
  page(
    "CRDTs",
    "alias:: CRDT",
    "tags:: local-first",
    "",
    "- every device edits its own copy, and merges always agree",
    `- why seqno needs one: ${ref(ids.loro)}`,
    "- Loro has the two structures an outliner needs: a movable tree, and rich text per node",
    "\t- moves are tree moves. two concurrent moves that would make a cycle can't",
    "\t- each block's text is its own text CRDT, so two people typing in one block merge by character",
    "- sync with no server:",
    `\t- {{embed ${ref(ids.oneWriter)}}}`,
    "- importing an op twice changes nothing, so a conflict copy from iCloud is harmless",
    "- read [[Martin Kleppmann]] on local-first, in [[reading]]",
  ),
  page(
    "motion design",
    "alias:: animation",
    "",
    "- feel matters as much as function",
    `- ${ref(ids.overshoot)}`,
    "- everything that moves should be interruptible. a slide reverses from where it is, it doesn't finish first",
    "- hover cards: 150 ms to open, then a 400 ms window where the next one opens instantly",
    "- TODO seqno's search palette and popups have no exit animation yet [[projects/seqno]]",
    "- read: [[Emil Kowalski]], and Apple's Designing Fluid Interfaces in [[reading]]",
  ),
  page(
    "dark mode",
    "- design both themes at once, not light first",
    "- blur needs different numbers per theme: dark 42% black at 8px, light 38% tint at 10px",
    "- a side-by-side is only fair with the same content and the same sidebar open on both sides",
    "- seqno's harness shoots 12 screens next to Logseq in both themes [[projects/seqno]]",
    `- the flash on load: ${dated(20240326)}, then [[projects/astro-fouc-killer]]`,
  ),
  page(
    "prompting",
    "- my prompt is the brief. a fresh agent gets it word for word, plus where the files are. no summary, no extra goals #rule",
    `- reword a few words before adding a rule: ${ref(ids.reword)}`,
    `- ${ref(ids.onlyNever)}`,
    "- small fast models for watching and wide searches, judgment stays with the big one. small models on max effort overthink",
    "- plain words. write so I can follow cold, I'm switching between a lot of projects",
    `- ${ref(ids.readTheCode)}`,
  ),
  page(
    "open source",
    "- my projects are public from the first commit, MIT",
    "- every commit signed. if signing breaks, fix signing",
    "- scope and design come from maintainers: what they said, merged or turned down",
    "- a PR a maintainer can decide on in a minute",
    "\t- what it does",
    "\t  logseq.order-list-type:: number",
    "\t- the decisions it makes",
    "\t  logseq.order-list-type:: number",
    "\t- big screenshots",
    "\t  logseq.order-list-type:: number",
    "- when I cite an issue, say who wrote it: a maintainer or someone from outside",
    "- release candidates from big, widely used projects are fine to build on",
    `- all my new code is open source, since ${dated(20260110)}`,
    `- my first PR to someone else's repo was one missing word: ${dated(20240129)}`,
  ),
  page(
    "naming",
    "- names are lowercase. one word if it fits, two at most",
    "- search a name before getting attached to it",
    "- commonplace took four rounds, see the storm on " + d.date(-4),
  ),
  page(
    "history",
    "- I love history as a whole",
    "- [[Rome]] most of all",
    "- Venice",
    `\t- ${yt("History Summarized: The Republic of Venice", "7cHK4xzAhzE")}, watched Feb 2023`,
    `\t- ${yt("The Mystery Of The Samurai In Venice", "8pkX2fLFy4E")}, Nerdwriter, Jan 2026`,
    `\t- the Doge was picked by ten rounds of lottery and vote: ${dated(20260811)}`,
    "- two Historia Civilis essays",
    `\t- ${yt("Work.", "hvk_XylEmLo")}: ${dated(20231002)}`,
    `\t- ${yt("The City.", "872JcpP3FEM")}: ${dated(20260315)}`,
    `\t- ${thumb("Work.", "hvk_XylEmLo")}`,
    "- LATER where and when work actually started, in detail",
    "- the Bronze Age collapse, the Congress of Vienna, the Year Without a Summer [[Historia Civilis]]",
    "- [[systems of power]]",
    "- channels: [[Historia Civilis]], Kings and Generals, Tribunate, Overly Sarcastic Productions, toldinstone, Invicta, Epic History, Premodernist",
  ),
  page(
    "Rome",
    "tags:: [[history]]",
    "",
    "- my handle, AVGVSTVS96, is Augustus in Roman capitals",
    "- the Caesar series from [[Historia Civilis]]: watched it in 2023, 2024 and 2026",
    `\t- ${dated(20230601)} · ${dated(20241209)} · ${dated(20260314)}`,
    `\t- ${thumb("Caesar Crosses the Rubicon", "SYxN134gb-8")}`,
    `- an Augustus afternoon: ${dated(20260301)}`,
    `- Tribunate on Sulla, the triumvirates and the six emperors: ${dated(20260406)}`,
    `- ${yt("How Rome Conquered Greece", "v5q1rerf-qw")}, Kings and Generals, two hours`,
  ),
  page(
    "systems of power",
    "alias:: governance",
    "",
    `- {{embed ${ref(ids.everySystem)}}}`,
    `- {{embed ${ref(ids.corruptible)}}}`,
    "- who gets power, and what it does to them",
    `\t- Corruptible, [[Brian Klaas]]. his Big Think talks first: ${dated(20230909)}, ${dated(20231013)}`,
    `\t- CGP Grey on the keys to power: ${dated(20260710)}`,
    "- systems that work",
    `\t- Switzerland's seven presidents: ${dated(20260619)}`,
    `\t- ${yt("How Switzerland Engineered the Perfect Country", "OMbV1rIPhCg")}, Johnny Harris, Jun 2026`,
    `\t- Venice's Doge election: ${dated(20260811)}`,
    "\t- ![the Doge selection chain](https://pbs.twimg.com/media/HPee_lnawAAdipq.jpg)",
    "- [[history]]",
  ),
  page(
    "philosophy",
    "- [[exurb1a]]: what we are is fickle, and in the end there's no real sense of self",
    `\t- ${dated(20260509)}`,
    `- every person's opinions make sense inside their own lived experience: ${d.date(-22)}`,
    `- "AGI" is still an LLM. or is consciousness just a loop of perception and reflection? ${dated(20260908)}`,
    `- ${yt("One must imagine Sisyphus happy", "J9elzJqlqfc")}`,
    "- argue against the best version of the other side: [the steel man technique](https://constantrenewal.com/steel-man)",
    "- Like Stories of Old and Pursuit of Wonder, on film and ideas",
    "- saved, to think about",
    `\t- ${yt("Something Weird Happens When You See How Connected Everything Is", "two4InjFSLs")}, Pursuit of Wonder: a toaster shows how interconnected civilization is`,
    `\t- ${yt("The Most Terrifying Theory Philosophers Don't Want to Talk About", "PXlWKV-dFr0")}, Pursuit of Wonder: a brain injury, and what it says about free will`,
    `\t- ${yt("Cormac McCarthy's Most Profound Story", "mxP1MeDYhrc")}, Like Stories of Old: a tale from The Crossing about a heretic, a priest and the meaning of life`,
    `\t- ${yt("Then Next Comes", "o1OsDWT_DUc")}, exurb1a: the far future, told through 100 objects`,
  ),
  page(
    "sci-fi",
    "- I'm a Three-Body Problem boy. a dark forest boy. no Fermi paradox, it's all the dark forest, and we'd be fools for yelling into the void",
    `  id:: ${ids.darkForest}`,
    `- ${ref(ids.thousandYears)}`,
    `- favorites, books and screen: The Three-Body Problem, Foundation, The Expanse, Dune. ${dated(20260909)}`,
    `- are people predictable, like in Foundation? yes, for sure. a huge topic of contention. ${dated(20230728)}`,
    `- There Is No Antimemetics Division: ${ref(ids.antimemetics)}`,
    "- Silo: quickly becoming one of my favorite sci-fi shows",
    `- ${thumb("Why We Should NOT Look For Aliens - The Dark Forest", "xAUJYP8tnRE")}`,
    "\t- Kurzgesagt on the dark forest, June 2022, two weeks after I found the books",
    "- channels: [[Quinn's Ideas]], [[Jacob Geller]], melodysheep, DUST",
    "- saved, to think about",
    `\t- ${yt("The Future is an Empty Room", "F0K2DnI1TDk")}, Jacob Geller: Death Stranding, The Veldt, and the empty futures sci-fi imagines`,
  ),
  page(
    "keyboards",
    "alias:: mechanical keyboards",
    "",
    "- every year since I started coding, a rabbit hole or two",
    `\t- ${dated(20230310)}: Mojo68, NuPhy Air75, hot-swap, Gazzew U4Tx`,
    `\t- ${dated(20230407)}: [[Ryan Norbauer]], Forgotten Futures`,
    `\t- ${dated(20240406)}: split boards, ortholinear`,
    `\t- ${dated(20240818)}: NuPhy Halo75 and Gem80, ceramic keycaps, a wireless Corne`,
    `\t- ${dated(20241115)}: Kinesis Advantage360, Keychron Q11`,
    `\t- ${dated(20250804)}: the Alice layout, Work Louder Nomad [E]`,
    "\t- Oct 2025: low profile, Lofree Flow, NuPhy Air75 V3",
    `\t- ${dated(20251022)}: a new keyboard, and a script for its battery life`,
    `- split keyboards are better for my wrists and worse for the sound: ${d.date(-24)}`,
    `- a Work Louder Codex Micro 2 macropad, driving herdr: ${dated(20260724)}`,
    `- ${video("EYGoXXNhj4U")}`,
  ),
  page(
    "design",
    "alias:: typography",
    "",
    '- "inspiration" is my biggest X bookmark folder, 440 posts',
    "- on my site",
    `\t- LCH for the rainbow: ${dated(20240419)}`,
    `\t- a 4x8 grid page and Inter: ${dated(20240505)}`,
    `\t- Astro's fonts API: ${dated(20250929)}`,
    "- components",
    `\t- Radix → AriaKit (${dated(20250626)}) → Base UI (${dated(20260706)})`,
    `\t- Tailwind v4: ${dated(20251113)}`,
    `- one good designer can carry a startup's brand: ${d.date(-16)}`,
    "- saved",
    `\t- ${bookmark("A new (or rather, old) approach to typography on the web", "1970847957625811207")}`,
    `\t- ${bookmark("The Proportional Web, after Bringhurst", "2075500277264744867")}`,
    `\t- ${bookmark("Interfaces, a design engineering magazine", "2054588519100645717")}`,
    `\t- ${bookmark("vintage annual report design", "2088105648521134168")}`,
    "\t- [Rauno's Web Interface Guidelines](https://interfaces.rauno.me), [Commit Mono](https://commitmono.com), [Maggie Appleton](https://maggieappleton.com)",
    `\t- ${yt("nodepad: a design experiment in spatial thinking", "jZu4sgZOOO4")}`,
    "- [[dark mode]] · [[motion design]] · [[Emil Kowalski]]",
  ),
  page(
    "making things",
    "alias:: 3D printing",
    "",
    `- Bambu Lab X2D: ${dated(20260911)}`,
    "\t- ![a mechanical under-desk charging mount, mid-print](https://pbs.twimg.com/media/HR7ZGP4boAAwEQI.jpg)",
    `- fuzzy skin test prints: ${d.date(-21)}`,
    `- ${yt("I Redesigned the Ugliest Thing on My Desk", "ljhDu1ov-c4")}. liked it`,
    `- LATER the YubiKey in sheet metal: ${dated(20260902)}`,
    `- small form factor PCs: ${dated(20260406)}`,
    `- a homelab on Omarchy: ${d.date(-24)}`,
  ),
  page(
    "racing",
    `- don't get to talk about it much: ${d.date(-5)}`,
    `- karting: ${dated(20250312)}`,
    `- ${yt("Robin Shute Pikes Peak 2026 Full Onboard", "nF9ESA_H2z8")}`,
    `- game feel: ${dated(20251111)}`,
    "- watching: Hagerty, OC Racing, Misha Charoudin at the Nürburgring",
    "- saved",
    `\t- ${bookmark("Bryan Johnson: car racing as cognitive training", "2106404568401682468")}`,
    `\t- ${bookmark("Tobi: racing as flow", "2106469972524359761")}`,
  ),
  page(
    "terminal",
    "alias:: tmux",
    "",
    "- tmux, then herdr. neovim on LazyVim. lazygit. Ghostty",
    `- I'd rather use a TUI than a GUI: ${dated(20250428)}`,
    "- what I built for it",
    "\t- [[projects/vim-herdr-navigator]] · [[projects/persistence-scope.nvim]] · [[projects/dotfiles]]",
    `\t- differential, a diff viewer: ${dated(20251012)}`,
    `\t- herdr-drovr: ${dated(20260622)}`,
    `- window managers: Niri on Linux, Spear on the Mac: ${d.date(-7)}`,
    `- first vim videos: ${dated(20230220)}`,
  ),
  page(
    "SF",
    "alias:: San Francisco",
    "",
    `- there's no other city like it if you're an engineer in love with the craft. ${dated(20250924)}`,
    `- dev events: ${dated(20251006)}, ${dated(20251111)}`,
    "- saved",
    `\t- ${bookmark("Envelop, a listening room with 32 speakers", "2088397433411653787")}`,
    `\t- ${bookmark("Yoshida, for framing art", "2081196513196388844")}`,
  ),
  page(
    "notes apps",
    `- ${ref(ids.logseqHole)}`,
    `- a Raycast extension for Obsidian QuickAdd: ${dated(20251129)}`,
    "- then I built my own: [[projects/openleaf]], [[projects/seqno]]",
  ),
  page(
    "watching",
    "alias:: YouTube",
    "",
    "- a lot of how I learned to code",
    "- [[Theo Browne]] most days since January 2024. [[ThePrimeagen]] before that",
    "- [[exurb1a]], [[Historia Civilis]], [[Jacob Geller]], [[Quinn's Ideas]], [[CGP Grey]]",
    "- also: Like Stories of Old, Pursuit of Wonder, Johnny Harris, Veritasium, melodysheep, Kings and Generals, Tribunate",
    "- saved, to come back to",
    `\t- ${yt("The Internet Was Weeks Away From Disaster And No One Knew", "aoag03mSuXQ")}, Veritasium: the xz backdoor`,
    `\t- ${yt("Philly ETE - Coda Hale - The Programming Ape", "e_6gkfTomUQ")}: humans aren't rational, and they build software anyway`,
  ),
]
