import type { StarterFile } from "../place.ts"
import { dated, ids, on, post, pr, ref, thumb, video, yt } from "./kit.ts"

export const y2026: ReadonlyArray<StarterFile> = [
  on(
    20260103,
    `- [[projects/openleaf]] gets a Typora-style editor, ProseMark, and Shiki for code blocks ${pr("AVGVSTVS96/openleaf", 10)}`,
  ),
  on(
    20260110,
    `- all my new code will always be 100% open source ${post("2009929579688014193")} [[open source]]`,
    "\t- if I have the choice, the ideal of open source beats monetizing it",
    "- OpenLeaf syncs through Convex now, conflicts settled by version numbers [[projects/openleaf]]",
  ),
  on(
    20260118,
    "- sign-in moves to /notes right after the mnemonic checks out. the key derives while a skeleton shows #decision #openleaf",
    "\t- creating a vault shows the mnemonic instantly, the crypto runs behind it",
    "\t- perceived speed: nothing waits on the crypto that doesn't have to",
    `\t- ${pr("AVGVSTVS96/openleaf", 19)}`,
    `- PR to lazyjj: pipe diffs through delta instead of \`--tool\`, so they stay inline [[terminal]] ${pr("cretezy/lazyjj", 195)}`,
    "- dotfiles on GNU Stow, secrets in sops. not Nix anymore #decision #dotfiles",
    `  id:: ${ids.offNix}`,
    `\t- on Nix every config change wants a rebuild-switch, unless every file goes through \`mkOutOfStoreSymlink\` ${post("2106293987304952283")}`,
    `\t- with Stow they're normal dots, edited in place ${post("2081793329554207005")}`,
    "\t- started stow-tui today, a little Rust TUI for managing them",
  ),
  on(
    20260209,
    "- OpenLeaf is Convex-only. Dexie and my own sync engine are gone #decision #openleaf",
    "\t- reactive Convex queries and mutations replace the local database and the sync layer",
    "\t- sync status is just the connection state now",
    `\t- ${pr("AVGVSTVS96/openleaf", 20)}`,
  ),
  on(
    20260301,
    "- an Augustus afternoon [[Rome]] [[history]]",
    `\t- ${yt("Augustus: How Rome's First Emperor Shaped the Empire's Future", "iQOS1oJNGz8")}, Kings and Generals`,
    `\t- ${yt("History RE-Summarized: The Age of Augustus", "H-iE-LlpCME")}, Overly Sarcastic Productions`,
    `\t- ${yt("The Death of Antony & Cleopatra", "EezHXh-UG-c")} [[Historia Civilis]]`,
    "\t- my handle, AVGVSTVS96, is Augustus in Roman capitals",
  ),
  on(
    20260302,
    `- speed upgrades feel bigger than intelligence upgrades now ${post("2028416715139502502")}`,
    "- react-shiki finds embedded languages with Shiki's `guessEmbeddedLanguages` and loads them first #decision #react-shiki",
    "\t- code inside a markdown block only highlighted if that language happened to be loaded already",
    `\t- ${pr("AVGVSTVS96/react-shiki", 127)}`,
    "- react-shiki publishes through npm trusted publishing (OIDC). no `NPM_TOKEN` #decision #react-shiki",
    "\t- releases kept failing on expired or OTP-blocked tokens",
    `\t- ${pr("AVGVSTVS96/react-shiki", 131)}`,
  ),
  on(20260305, `- watched ${yt("Work.", "hvk_XylEmLo")} again [[Historia Civilis]]`),
  on(
    20260314,
    "- seven Historia Civilis episodes in one day: Caesar in Gaul, again [[Historia Civilis]] [[Rome]]",
    `\t- ${yt("Vercingetorix", "lMFiED6sAi8")}`,
  ),
  on(
    20260315,
    `- ${yt("The City.", "872JcpP3FEM")} [[Historia Civilis]]`,
    "\t- love it. got me thinking at a bigger, societal scale. added a lot to the way I think [[history]]",
    `\t- ${video("872JcpP3FEM")}`,
    `- ${yt("The Scariest Book I've Read in Years | There Is No Antimemetics Division", "xGqnfsGj4eM")} [[Quinn's Ideas]]`,
    "\t- MUST READ, MUST READ, MUST READ",
    `\t  id:: ${ids.antimemetics}`,
  ),
  on(20260319, `- liked ${yt("One must imagine Sisyphus happy", "J9elzJqlqfc")} [[philosophy]]`),
  on(
    20260406,
    "- Tribunate binge: Sulla, the first triumvirate, the year of the six emperors, the Praetorian Guard [[Rome]]",
    `\t- ${yt("Sulla, Rome's Bloodiest Dictator", "RClu7ADAcb4")}`,
    `\t- ${yt("The Year of the Six Emperors", "pNImOXD1hLU")}`,
    "- small form factor PC rabbit hole: NCASE M2, Fractal Terra, 5090s in tiny cases",
    `\t- ${yt("The holy grail of PC cases - NCASE M2.", "MsoEEb8_0OY")}`,
  ),
  on(
    20260411,
    `- ${yt("I Hated Every Coding Agent, So I Built My Own", "Dli5slNaJu0")}, Mario Zechner on pi`,
  ),
  on(
    20260414,
    "- [x-marks](https://github.com/AVGVSTVS96/x-marks): a viewer for my X bookmarks and their folders, on Convex",
    "\t- navigating between folders refetched every time. it needs a cache #bug",
  ),
  on(
    20260421,
    `- ${yt("You should start a commonplace book today", "L9awVwLDH18")}, Tom Harari [[projects/commonplace]]`,
  ),
  on(
    20260422,
    `- ${yt("nodepad: a design experiment in spatial thinking", "jZu4sgZOOO4")} [[design]]`,
  ),
  on(
    20260503,
    "- react-shiki: experimental `outputFormat: 'tokens'`, hook-only #decision #react-shiki",
    "\t- the component's value is its default styles, line numbers and HTML fast path. all of that assumes react-shiki's markup, which is gone once you render tokens yourself",
    "\t- the return type narrows from the `outputFormat` you pass, and the public options type didn't change",
    `\t- ${pr("AVGVSTVS96/react-shiki", 146)}`,
  ),
  on(
    20260509,
    `- new exurb1a, ${yt("maybe I'm the alien", "y894m7joEBc")}. I absolutely love it [[exurb1a]] [[philosophy]]`,
    "\t- our reality, and how we see ourselves, is shaped by our experiences and completely subjective",
    "\t- what we are is fickle: experiences, feelings and emotions at any given moment, with barely any control over it. in the end, no real sense of self",
    "\t- this is what exurb1a is really about",
    `\t- ${video("y894m7joEBc")}`,
  ),
  on(
    20260518,
    "- persistence-scope.nvim, first release #decision #persistence-scope",
    "\t- sessions are scoped to what I'm working in: the tmux session by default, anything else through a provider",
    "\t- built on folke's persistence.nvim, not a replacement for it",
    `\t- ${pr("AVGVSTVS96/persistence-scope.nvim", 1)}`,
  ),
  on(
    20260522,
    "- [pi-patcher](https://github.com/AVGVSTVS96/pi-patcher): write a PATCH.md once and my pi patches heal themselves after updates [[projects/PATCH.md]]",
  ),
  on(
    20260525,
    `- react-shiki/core rebuilt its highlighter factory every render and froze on mount #bug [[projects/react-shiki]] ${pr("AVGVSTVS96/react-shiki", 163)}`,
  ),
  on(
    20260605,
    "- prompt-picker: filters are the user's own code in the config, with a clean API, not built-in features #decision #prompt-picker",
    "\t- I want to hide some of my own prompts. that's my use case, not a feature everyone should get",
    "\t- of the two shapes, picked the one with the cleanest, best-looking code",
  ),
  on(
    20260613,
    `- open models are about a year behind on genuinely complex, many-sided tasks ${post("2065698675373003220", "57 likes")}`,
  ),
  on(
    20260615,
    `- tried herdr yesterday. polished, fast [[terminal]] ${post("2066535497066012716")}`,
  ),
  on(
    20260619,
    `- ${yt("Why Seven Presidents is Better than One", "6TQs2npDqUk")}, Spectacles. love it [[systems of power]]`,
    "\t- the video's case: Switzerland has seven presidents, and it works",
    `\t- ${thumb("Why Seven Presidents is Better than One", "6TQs2npDqUk")}`,
  ),
  on(
    20260622,
    "- [herdr-drovr](https://github.com/AVGVSTVS96/herdr-drovr): move herdr panes and tabs around easily [[terminal]]",
  ),
  on(
    20260624,
    "- PATCH.md: a patch is plain-prose intent plus edits anchored on content, never line numbers #decision #patch-md",
    `  id:: ${ids.patchFormat}`,
    "\t- when the upstream file drifts, an agent can read the intent and re-derive the patch",
    "\t- search/replace or diff hunks, both anchored on the code itself",
  ),
  on(
    20260702,
    "- launched vim-herdr-navigator [[projects/vim-herdr-navigator]]",
    "\t- ![vim-herdr-navigator README](https://pbs.twimg.com/media/HMOKa8SaEAA6DQ9.jpg)",
    `\t- noticed it was 5am ${post("2072654328226336933")}`,
    `\t- Dillon Mulroy sent a PR, built it ${post("2072653991939600532")}`,
    "- near parity with vim-tmux-navigator: Ctrl-h/j/k/l moves across vim splits and herdr panes as if they were one grid #decision #vim-herdr-navigator",
    "\t- editor windows get the first chance, herdr takes over when the cursor hits an edge",
    "- two halves in one repo: the vim/neovim plugin, and a small Rust binary that herdr keybindings call #decision #vim-herdr-navigator",
    "\t- the plugin ships Lua and classic Vimscript adapters. the herdr side is one small helper",
  ),
  on(
    20260703,
    `- I can trust the model's judgment now. no babysitting, it meets my bar. vim-herdr-navigator went out in ~30 minutes and ~5 prompts ${post("2072918328709087628")}`,
    "- react-shiki's CSS layer is `@layer react-shiki` now, not `@layer base` #decision #react-shiki",
    "\t- Tailwind v3's PostCSS plugin reserves `@layer base`. any Tailwind v3 app importing our CSS failed to compile",
    `\t- ${pr("AVGVSTVS96/react-shiki", 169)}`,
  ),
  on(
    20260704,
    "- no layer at all: react-shiki's defaults are unlayered `:where()` rules #decision #react-shiki",
    `  id:: ${ids.whereStyles}`,
    "\t- layer priority is fixed by whichever stylesheet declares it first. our CSS is injected by JS, so apps can't control that, and dev and prod bundled it in different orders",
    "\t- when our layer registered first, Tailwind v4's preflight stripped the padding off every code block",
    "\t- `:where()` has zero specificity, so any user rule wins, every time",
    `\t- ${pr("AVGVSTVS96/react-shiki", 174)}`,
  ),
  on(
    20260705,
    "- how much of the code should I read? in proportion to how many people a mistake would hurt #rule",
    `  id:: ${ids.readTheCode}`,
    "\t- every LLM does stupid things sometimes. if people use what I maintain, I read at least some of it",
    `\t- ${post("2073874228525547569")}`,
  ),
  on(
    20260706,
    `- Base UI is more fleshed out than Radix. it should be the default everywhere, and I'm going to push for it ${post("2074005889800159343")} [[design]]`,
    `- vim-herdr-navigator extras: it doesn't get stuck when an explorer or picker is open, and entering vim can focus the split nearest the side you came from ${post("2074009154805776873")} [[projects/vim-herdr-navigator]]`,
  ),
  on(
    20260709,
    "- forked steipete's CodexBar into a smaller one [[projects/codexbar]]",
    "- each provider is config, not code #decision #codexbar",
    "\t- I need to see my Claude and Codex usage, always. a minimal, modular fork is easier to keep reliable and to extend",
  ),
  on(
    20260710,
    `- ${yt("Try to Rule Fairly and You'll Be Overthrown", "rStL7niR7gs")} [[CGP Grey]] [[systems of power]]`,
    "\t- love the conflict between self-governance and human nature",
    "\t- positions of power are inherently corrupting, and they also attract particularly corruptible people",
    `\t  id:: ${ids.corruptible}`,
    "\t- same thread as Corruptible, the [[Brian Klaas]] audiobook I bought a while back [[reading]]",
    "\t\t- New Zealand's police recruiting ads go after people who want to do good and make a difference. American ones lean on cops, the military, military vehicles and guns. different ads attract different people",
    "\t\t- the Stanford prison experiment probably drew the worst of the worst on that campus, because of how it was advertised. a self-selection bias nobody talks about",
    '\t\t- [Carnahan & McFarland, 2007](https://pubmed.ncbi.nlm.nih.gov/17440210/) tested it: the same ad with "prison life" in it drew more aggressive, authoritarian applicants than the one without',
    "\t- a great thing to expand on, in several different ways and places",
    `\t- ${video("rStL7niR7gs")}`,
  ),
  on(
    20260712,
    `- I want a brain-computer interface. just know what every agent is doing and what it needs from me, and steer with thought ${post("2076132216326029750")}`,
    "- starter-dotfiles, for a friend who isn't technical but wants to build with AI #decision #dotfiles",
    "\t- sops + age, so secrets are easy to encrypt",
    "\t- agent skills and docs in the repo, so the agents maintain it",
    "\t- one command installs and sets up everything",
    `\t- [repo](https://github.com/AVGVSTVS96/starter-dotfiles) · ${post("2076226188746654179")}`,
    "- [pi-context-control](https://github.com/AVGVSTVS96/pi-context-control): per-message token usage in pi, mask anything in or out of context, swap a span for a short summary",
  ),
  on(
    20260717,
    `- posted the systems of power thing on X ${post("2078257803190563147")} [[systems of power]]`,
    "\t- people argue about which system is the right one. every system is flawed. human self-governance is a hard, society-sized problem",
    `\t  id:: ${ids.everySystem}`,
    `\t- goes with the Spectacles video on Switzerland's seven presidents, ${dated(20260619)}`,
    `- my dream: sleep and wake up in 100 or 1,000 years. I desperately want to see what humanity's future looks like ${post("2078242354847494402")} ${ref(ids.thousandYears)}`,
    "- react-shiki's CSS ships inside the JS and installs itself, scoped to what you use #decision #react-shiki",
    "\t- since the tsdown move, the published JS started with `import './style.css'`. plain Node ESM crashed, CDN use broke, webpack prod builds dropped the styles",
    "\t- component styles install on first mount, line-number styles only when you turn them on, and hook-only bundles tree-shake the CSS away",
    `\t- ${pr("AVGVSTVS96/react-shiki", 188)} · ${pr("AVGVSTVS96/react-shiki", 189)}`,
  ),
  on(20260718, `- i love electron ${post("2078611332681883699")}`),
  on(
    20260722,
    `- open question: should dev tools ship skills, or their docs next to the code? ${post("2079835124942913911")} #question`,
  ),
  on(
    20260724,
    "- new Work Louder Codex Micro 2. teaching it to drive herdr over HID [[keyboards]] [[terminal]]",
  ),
  on(
    20260808,
    `- chats from a year ago read better. the smarter the models got, the more jargon ${post("2085994588401967539")} [[prompting]]`,
    `- my herdr fork tracks upstream, re-applies its PATCH.md patches and cuts nightlies. one patch adds pane id labels ${post("2085914855119396958")} [[projects/PATCH.md]]`,
    "\t- a fun excuse to test automating repo maintenance",
  ),
  on(
    20260810,
    `- I like software. I wanna build a lot of really cool stuff. there's just not enough time ${post("2086727769694900227")}`,
  ),
  on(
    20260811,
    "- better-github-skill is out [[projects/better-github-skill]]",
    "\t- ![better-github-skill](https://pbs.twimg.com/media/HPeZNwTbAAAw3Xh.jpg)",
    "- scripts for what agents fumble with raw `gh` #decision #better-github-skill",
    "\t- `pr-snapshot`: one call instead of the 3-5 call `pr view --json` loop",
    "\t- `pr-threads`: one call instead of the 15-line GraphQL query agents keep retyping",
    `\t- faster, and it burns less context ${post("2087308821798715724", "108 likes")}`,
    "- the skill file stays minimal, written from mistakes I found across thousands of my own transcripts #decision #better-github-skill",
    `\t- ${post("2107956170799665541")}`,
    `- nobody talks about the Venetian Republic enough. the Doge was picked by ten rounds of lottery and vote ${post("2087311770621006298")} [[history]] [[systems of power]]`,
    "\t- ![the Doge selection chain](https://pbs.twimg.com/media/HPee_lnawAAdipq.jpg)",
  ),
  on(
    20260818,
    `- new exurb1a, ${yt("If We Ever Live Forever", "LoakcQM-Dk8")}, the day it came out [[exurb1a]]`,
    `\t- didn't change anything. still want to wake up in 1,000 years ${ref(ids.thousandYears)}`,
  ),
  on(
    20260830,
    "- skills are overrated, and often misused. if you ship a dev tool, ship docs with the source instead #rule",
    "\t- `-h` help text for CLIs, with a link to the docs",
    "\t- a docs site that returns markdown to agents",
    "\t- skills add a layer of documentation, indirection and complexity",
    `\t- ${post("2093913029440422217")}. answers my own question from ${dated(20260722)}`,
    `- if my agent can't fix it and I have to call support, someone will build the thing that fixes that ${post("2093941751283425326")}`,
  ),
  on(
    20260902,
    `- LATER wrap a YubiKey in some nicely finished sheet metal ${post("2094979690914255115")} [[making things]]`,
  ),
  on(
    20260903,
    `- suspended animation in the next 50 years? I want to see what a million years from now looks like ${post("2095537134908395561")}`,
  ),
  on(
    20260906,
    `- how do friends who can't afford an AI subscription get the same capability? I know smart people limited only by that ${post("2096413943841562791")}`,
  ),
  on(
    20260908,
    `- "AGI" is still an LLM in a harness. the LLM feels more like a building block ${post("2097472449952809206")} [[philosophy]]`,
    "\t- what if 1,000 fast agents were neurons, in a harness shaped like a brain, with an input or two",
    `\t- or am I just trying to recreate consciousness? a loop between perception and reflection ${post("2097472819496104241")}`,
  ),
  on(
    20260909,
    `- I was in the perfect frame of mind for the Silo season 3 finale ${post("2097478200406532376")} [[sci-fi]]`,
    `- favorites: The Three-Body Problem, Foundation, The Expanse, Dune. books and screen ${post("2097480428546597048")}`,
  ),
  on(
    20260911,
    `- Bambu Lab X2D. didn't want to like it, closed ecosystem, but unboxing to first print just works ${post("2098353180765794367")} [[making things]]`,
    "\t- ![a mechanical under-desk charging mount, mid-print](https://pbs.twimg.com/media/HR7ZGP4boAAwEQI.jpg)",
  ),
]
